import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const _localizedValues = {
    'en': {
      'app_title': 'Adeen • عدين',
      'sehri': 'Sehri Ends',
      'iftar': 'Iftar Time',
      'fajr': 'Fajr',
      'sunrise': 'Sunrise',
      'dhuhr': 'Dhuhr',
      'asr': 'Asr',
      'maghrib': 'Maghrib',
      'isha': 'Isha',
      'imsak': 'Imsak',
      'prayer_tracker': 'Daily Prayers Tracker',
      'qaza_tracker': 'Qaza Tracker',
      'fasting_tracker': 'Ramadan Fasting Tracker',
      'fasted_today': 'Fasting Today?',
      'fasting_completed': 'Alhamdulillah, Fast Completed!',
      'fasting_not_completed': 'Fast not started/logged yet',
      'prayers_logged': 'Prayers Logged',
      'mosques': 'Nearby Mosques',
      'search_mosques': 'Filter Mosques by Facility',
      'facility_women': 'Women\'s Section',
      'facility_parking': 'Parking Space',
      'facility_jummah': 'Multiple Jummah Shifts',
      'iqamah_time': 'Iqamah',
      'suggest_iqamah': 'Suggest Iqamah Update',
      'get_directions': 'Get Directions',
      'update_iqamah_title': 'Suggest Iqamah Time',
      'update_success': 'Iqamah time updated successfully!',
      'enter_time': 'Select Time',
      'cancel': 'Cancel',
      'save': 'Save',
      'distance': 'Distance',
      'km': 'km',
      'method': 'Calculation Method',
      'next_prayer_in': 'Next Prayer in',
      'sehri_ends_in': 'Sehri ends in',
      'iftar_in': 'Iftar starts in',
      'offline_msg': 'Offline Mode • Local Cache',
      'loading': 'Updating prayer times...',
      'bismillah': 'In the name of Allah, the Beneficent, the Merciful',
      'change_lang': 'Language / ভাষা / اللغة',
      'active_lang': 'English',
      'settings': 'Settings & Preferences',
      'theme_mode': 'Theme Mode',
      'theme_system': 'System Default',
      'theme_light': 'Light Mode',
      'theme_dark': 'Dark Mode',
      'color_scheme': 'Color Preset Schema',
      'color_emerald': 'Emerald Green',
      'color_sapphire': 'Sapphire Blue',
      'color_ruby': 'Ruby Red',
      'profile': 'User Profile & Statistics',
      'stats_weekly_prayers': 'Weekly Prayers Completed',
      'stats_weekly_fasts': 'Fasts Logged (Last 7 days)',
      'qaza_backlog': 'Active Qaza Backlog',
      'back_to_home': 'Back to Home',
      'active_preset': 'Active Color Theme',
      'completed': 'completed',
      'days': 'days',
      'of_total': 'of',
      'exit_warning': 'Press back again to exit',
      'current_prayer': 'Current Prayer',
      'next_prayer': 'Next Prayer',
      'left': 'left',
      'time_elapsed': 'elapsed',
      'remaining': 'remaining',
      'quiz': 'Quranic Quiz',
      'tafsir_review': 'Tafsir Review',
      'quiz_question_count': 'Question',
      'quiz_points': 'Points',
      'quiz_next': 'Next Question',
      'quiz_previous': 'Previous',
      'quiz_finish': 'Finish Quiz',
      'quiz_lifetime_score': 'Lifetime Score',
      'quiz_completed_title': 'Daily Quiz Completed!',
      'quiz_completed_sub': 'You have answered all 7 questions for today. Come back tomorrow for a new set of Quranic insights!',
      'quiz_syncing': 'Syncing progress with server...',
      'quiz_synced': 'Progress securely synced to cloud',
      'quiz_correct': 'Correct',
      'quiz_incorrect': 'Incorrect',
      'quiz_tafsir_insight': 'Tafsir Insight',
      'quiz_pts': 'pts',
      'no_questions_available': 'No Questions Available',
      'no_questions_available_sub': 'There are no questions configured for today. Please try again later.',
      'quiz_no_results': "No results available. Please complete today's quiz first.",
      'quiz_sync_error_timeout': 'Connection timed out. Progress saved locally.',
      'quiz_sync_error_failed': 'Sync failed. Progress saved locally.',
      'explore_tools': 'Spiritual Hub',
      'hub_mosques_sub': 'Find nearby mosques',
      'hub_quiz_sub': 'Test Quranic insights',
      'hub_tracker_sub': 'Log daily prayers',
      'hub_qaza_sub': 'Track missed prayers',
      'hub_profile_sub': 'View stats & log',
      'hub_settings_sub': 'Themes & calculation',
      'special_timings': 'Special Timings & Prohibited Periods',
      'forbidden_status': 'Prayer Permission Status',
      'prayer_allowed': 'All prayers are permitted',
      'prayer_forbidden': 'Voluntary prayers are prohibited',
      'tahajjud_prayer': 'Tahajjud Prayer',
      'tahajjud_desc': 'Night vigil prayer',
      'tahajjud_best': 'Tahajjud (Best Time)',
      'ishraq_prayer': 'Ishraq Prayer',
      'ishraq_desc': 'Early morning prayer',
      'forbidden_sunrise': 'Sunrise Forbidden Period',
      'forbidden_zawal': 'Zawal (Midday) Forbidden',
      'forbidden_sunset': 'Sunset Forbidden Period',
      'tahajjud_active': 'Tahajjud Time is Active',
      'ishraq_active': 'Ishraq Time is Active',
    },
    'ar': {
      'app_title': 'عدين • Adeen',
      'sehri': 'نهاية السحور',
      'iftar': 'وقت الإفطار',
      'fajr': 'الفجر',
      'sunrise': 'الشروق',
      'dhuhr': 'الظهر',
      'asr': 'العصر',
      'maghrib': 'المغرب',
      'isha': 'العشاء',
      'imsak': 'الإمساك',
      'prayer_tracker': 'مصحح الصلوات اليومية',
      'qaza_tracker': 'متابعة صلوات القضاء',
      'fasting_tracker': 'متابعة الصيام الرمضاني',
      'fasted_today': 'صائم اليوم؟',
      'fasting_completed': 'الحمد لله، تم الصيام!',
      'fasting_not_completed': 'لم يبدأ الصوم/لم يسجل بعد',
      'prayers_logged': 'الصلوات المسجلة',
      'mosques': 'المساجد القريبة',
      'search_mosques': 'تصفية المساجد حسب المرافق',
      'facility_women': 'مصلى للنساء',
      'facility_parking': 'مواقف سيارات',
      'facility_jummah': 'خطب جمعة متعددة',
      'iqamah_time': 'الإقامة',
      'suggest_iqamah': 'اقتراح تعديل وقت الإقامة',
      'get_directions': 'الحصول على الاتجاهات',
      'update_iqamah_title': 'اقتراح وقت الإقامة',
      'update_success': 'تم تحديث وقت الإقامة بنجاح!',
      'enter_time': 'اختر الوقت',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'distance': 'المسافة',
      'km': 'كم',
      'method': 'طريقة الحساب',
      'next_prayer_in': 'الصلاة القادمة خلال',
      'sehri_ends_in': 'ينتهي السحور خلال',
      'iftar_in': 'يبدأ الإفطار خلال',
      'offline_msg': 'وضع غير متصل بالإنترنت • ذاكرة التخزين المؤقت',
      'loading': 'جاري تحديث أوقات الصلاة...',
      'bismillah': 'بسم الله الرحمن الرحيم',
      'change_lang': 'اللغة / Language / ভাষা',
      'active_lang': 'العربية',
      'settings': 'الإعدادات والتفضيلات',
      'theme_mode': 'مظهر التطبيق',
      'theme_system': 'تلقائي النظام',
      'theme_light': 'المظهر الفاتح',
      'theme_dark': 'المظهر الداكن',
      'color_scheme': 'سمة الألوان والمظهر',
      'color_emerald': 'الأخضر الزمردي',
      'color_sapphire': 'الأزرق الياقوتي',
      'color_ruby': 'الأحمر الياقوتي',
      'profile': 'ملف المستخدم والإحصائيات',
      'stats_weekly_prayers': 'الصلوات المؤداة هذا الأسبوع',
      'stats_weekly_fasts': 'أيام الصيام (آخر ٧ أيام)',
      'qaza_backlog': 'الصلوات الفائتة النشطة',
      'back_to_home': 'العودة للرئيسية',
      'active_preset': 'سمة الألوان النشطة',
      'completed': 'مكتملة',
      'days': 'أيام',
      'of_total': 'من أصل',
      'exit_warning': 'اضغط مرة أخرى للخروج',
      'current_prayer': 'الصلاة الحالية',
      'next_prayer': 'الصلاة القادمة',
      'left': 'متبقي',
      'time_elapsed': 'منقضي',
      'remaining': 'متبقي',
      'quiz': 'الاختبار القرآني',
      'tafsir_review': 'مراجعة التفسير',
      'quiz_question_count': 'سؤال',
      'quiz_points': 'نقاط',
      'quiz_next': 'السؤال التالي',
      'quiz_previous': 'السابق',
      'quiz_finish': 'إنهاء الاختبار',
      'quiz_lifetime_score': 'النتيجة الإجمالية',
      'quiz_completed_title': 'اكتمل الاختبار اليومي!',
      'quiz_completed_sub': 'لقد أجبت على جميع الأسئلة السبعة لهذا اليوم. عد غدًا لمجموعة جديدة من الأفكار القرآنية!',
      'quiz_syncing': 'مزامنة التقدم مع الخادم...',
      'quiz_synced': 'تمت مزامنة التقدم بأمان مع السحابة',
      'quiz_correct': 'صحيح',
      'quiz_incorrect': 'غير صحيح',
      'quiz_tafsir_insight': 'بصيرة التفسير',
      'quiz_pts': 'نقاط',
      'no_questions_available': 'لا توجد أسئلة متاحة',
      'no_questions_available_sub': 'لا توجد أسئلة مخصصة لهذا اليوم. يرجى المحاولة لاحقاً.',
      'quiz_no_results': 'لا توجد نتائج متاحة. يرجى إكمال اختبار اليوم أولاً.',
      'quiz_sync_error_timeout': 'انتهت مهلة الاتصال. تم حفظ التقدم محلياً.',
      'quiz_sync_error_failed': 'فشلت المزامنة. تم حفظ التقدم محلياً.',
      'explore_tools': 'المركز الروحي',
      'hub_mosques_sub': 'ابحث عن المساجد القريبة',
      'hub_quiz_sub': 'اختبر معلوماتك القرآنية',
      'hub_tracker_sub': 'سجل صلواتك اليومية',
      'hub_qaza_sub': 'تابع صلوات القضاء',
      'hub_profile_sub': 'عرض الإحصائيات والسجل',
      'hub_settings_sub': 'المظاهر وطرق الحساب',
      'special_timings': 'الأوقات الخاصة والفترات المنهي عنها',
      'forbidden_status': 'حالة إذن الصلاة',
      'prayer_allowed': 'جميع الصلوات مسموح بها',
      'prayer_forbidden': 'الصلوات التطوعية منهي عنها',
      'tahajjud_prayer': 'صلاة التهجد',
      'tahajjud_desc': 'صلاة قيام الليل',
      'tahajjud_best': 'التهجد (أفضل وقت)',
      'ishraq_prayer': 'صلاة الإشراق',
      'ishraq_desc': 'صلاة أول النهار',
      'forbidden_sunrise': 'وقت الكراهة (عند الشروق)',
      'forbidden_zawal': 'وقت الكراهة (عند الزوال)',
      'forbidden_sunset': 'وقت الكراهة (عند الغروب)',
      'tahajjud_active': 'وقت التهجد نشط الآن',
      'ishraq_active': 'وقت الإشراق نشط الآن',
    },
    'bn': {
      'app_title': 'আদীন • Adeen',
      'sehri': 'সেহরি শেষ',
      'iftar': 'ইফতারের সময়',
      'fajr': 'ফজর',
      'sunrise': 'সূর্যোদয়',
      'dhuhr': 'যোহর',
      'asr': 'আসর',
      'maghrib': 'মাগরিব',
      'isha': 'এশা',
      'imsak': 'ইমসাক',
      'prayer_tracker': 'দৈনিক সালাত ট্র্যাকার',
      'qaza_tracker': 'কাযা সালাত ট্র্যাকার',
      'fasting_tracker': 'রোজা ট্র্যাকার',
      'fasted_today': 'আজ রোজা আছেন?',
      'fasting_completed': 'আলহামদুলিল্লাহ, রোজা সম্পন্ন!',
      'fasting_not_completed': 'রোজা শুরু/লগ করা হয়নি',
      'prayers_logged': 'লগ করা সালাত',
      'mosques': 'নিকটবর্তী মসজিদ',
      'search_mosques': 'সুবিধা অনুযায়ী মসজিদ ফিল্টার',
      'facility_women': 'মহিলাদের নামাজের জায়গা',
      'facility_parking': 'পার্কিং এর ব্যবস্থা',
      'facility_jummah': 'একাধিক জুম্মা জামাত',
      'iqamah_time': 'ইকামত',
      'suggest_iqamah': 'ইকামত পরিবর্তনের অনুরোধ',
      'get_directions': 'দিকনির্দেশনা পান',
      'update_iqamah_title': 'ইকামত সময় আপডেট',
      'update_success': 'ইকামত সময় সফলভাবে আপডেট হয়েছে!',
      'enter_time': 'সময় নির্বাচন করুন',
      'cancel': 'বাতিল',
      'save': 'সংরক্ষণ',
      'distance': 'দূরত্ব',
      'km': 'কি.মি.',
      'method': 'গণনা পদ্ধতি',
      'next_prayer_in': 'পরবর্তী সালাত শুরু',
      'sehri_ends_in': 'সেহরি শেষ হতে',
      'iftar_in': 'ইফতার শুরু হতে',
      'offline_msg': 'অফলাইন মোড • লোকাল ক্যাশ',
      'loading': 'সালাতের সময় আপডেট হচ্ছে...',
      'bismillah': 'পরম করুণাময় ও অসীম দয়ালু আল্লাহর নামে',
      'change_lang': 'ভাষা পরিবর্তন / Language',
      'active_lang': 'বাংলা',
      'settings': 'সেটিংস এবং পছন্দসমূহ',
      'theme_mode': 'থিম মোড',
      'theme_system': 'সিস্টেম ডিফল্ট',
      'theme_light': 'লাইট মোড',
      'theme_dark': 'ডার্ক মোড',
      'color_scheme': 'কালার স্কিম',
      'color_emerald': 'পান্না সবুজ (Emerald)',
      'color_sapphire': 'নীলকান্তমণি (Sapphire)',
      'color_ruby': 'চুনি লাল (Ruby)',
      'profile': 'ব্যবহারকারীর প্রোফাইল এবং পরিসংখ্যান',
      'stats_weekly_prayers': 'সাপ্তাহিক সালাত সম্পন্ন',
      'stats_weekly_fasts': 'সাপ্তাহিক রোজা সম্পন্ন (গত ৭ দিন)',
      'qaza_backlog': 'সক্রিয় কাযা সালাত',
      'back_to_home': 'হোমে ফিরে যান',
      'active_preset': 'সক্রিয় কালার থিম',
      'completed': 'সম্পন্ন',
      'days': 'দিন',
      'of_total': 'এর মধ্যে',
      'exit_warning': 'অ্যাপ থেকে বের হতে আবার ব্যাক প্রেস করুন',
      'current_prayer': 'বর্তমান সালাত',
      'next_prayer': 'পরবর্তী সালাত',
      'left': 'বাকি',
      'time_elapsed': 'অতিবাহিত',
      'remaining': 'অবশিষ্ট',
      'quiz': 'কোরআনিক কুইজ',
      'tafsir_review': 'তাফসীর পর্যালোচনা',
      'quiz_question_count': 'প্রশ্ন',
      'quiz_points': 'পয়েন্ট',
      'quiz_next': 'পরবর্তী প্রশ্ন',
      'quiz_previous': 'পূর্ববর্তী',
      'quiz_finish': 'কুইজ শেষ করুন',
      'quiz_lifetime_score': 'আজীবন স্কোর',
      'quiz_completed_title': 'আজকের কুইজ সম্পন্ন!',
      'quiz_completed_sub': 'আপনি আজকের ৭টি প্রশ্নের সবগুলোর উত্তর দিয়েছেন। নতুন কোরআনিক অন্তর্দৃষ্টির জন্য আগামীকাল আবার আসুন!',
      'quiz_syncing': 'সার্ভারের সাথে প্রগতি সিঙ্ক করা হচ্ছে...',
      'quiz_synced': 'প্রগতি ক্লাউডের সাথে নিরাপদে সিঙ্ক হয়েছে',
      'quiz_correct': 'সঠিক',
      'quiz_incorrect': 'ভুল',
      'quiz_tafsir_insight': 'তাফসীর অন্তর্দৃষ্টি',
      'quiz_pts': 'পয়েন্ট',
      'no_questions_available': 'কোন প্রশ্ন উপলব্ধ নেই',
      'no_questions_available_sub': 'আজকের জন্য কোন প্রশ্ন কনফিগার করা নেই। অনুগ্রহ করে পরে আবার চেষ্টা করুন।',
      'quiz_no_results': 'কোন ফলাফল উপলব্ধ নেই। অনুগ্রহ করে প্রথমে আজকের কুইজটি সম্পূর্ণ করুন।',
      'quiz_sync_error_timeout': 'সংযোগের সময় শেষ হয়েছে। প্রগতি লোকালি সংরক্ষণ করা হয়েছে।',
      'quiz_sync_error_failed': 'সিঙ্ক ব্যর্থ হয়েছে। প্রগতি লোকালি সংরক্ষণ করা হয়েছে।',
      'explore_tools': 'আধ্যাত্মিক হাব',
      'hub_mosques_sub': 'নিকটবর্তী মসজিদ খুঁজুন',
      'hub_quiz_sub': 'কোরআনিক জ্ঞান পরীক্ষা করুন',
      'hub_tracker_sub': 'দৈনিক সালাত লগ করুন',
      'hub_qaza_sub': 'কাযা সালাত ট্র্যাক করুন',
      'hub_profile_sub': 'পরিসংখ্যান ও লগ দেখুন',
      'hub_settings_sub': 'থিম ও গণনা পদ্ধতি',
      'special_timings': 'বিশেষ নামাজ ও নিষিদ্ধ সময়',
      'forbidden_status': 'নামাজ পড়ার অনুমতি',
      'prayer_allowed': 'সব সালাত আদায় করা যাবে',
      'prayer_forbidden': 'নফল সালাত আদায় করা নিষিদ্ধ',
      'tahajjud_prayer': 'তাহাজ্জুদ সালাত',
      'tahajjud_desc': 'রাতের শেষভাগের সালাত',
      'tahajjud_best': 'তাহাজ্জুদ (উত্তম সময়)',
      'ishraq_prayer': 'ইশরাক সালাত',
      'ishraq_desc': 'সূর্যোদয়ের পরের সালাত',
      'forbidden_sunrise': 'সূর্যোদয়ের নিষিদ্ধ সময়',
      'forbidden_zawal': 'জাওয়াল (দ্বিপ্রহর) নিষিদ্ধ সময়',
      'forbidden_sunset': 'সূর্যাস্তের নিষিদ্ধ সময়',
      'tahajjud_active': 'তাহাজ্জুদের সময় চলছে',
      'ishraq_active': 'ইশরাকের সময় চলছে',
    },
    'hi': {
      'app_title': 'अदीन • Adeen',
      'sehri': 'सेहरी समाप्ति',
      'iftar': 'इफ्तार का समय',
      'fajr': 'फज्र',
      'sunrise': 'सूर्योदय',
      'dhuhr': 'धुहर',
      'asr': 'असर',
      'maghrib': 'मग़रिब',
      'isha': 'ईशा',
      'imsak': 'इमसाक',
      'prayer_tracker': 'दैनिक प्रार्थना ट्रैकर',
      'qaza_tracker': 'कज़ा ट्रैकर',
      'fasting_tracker': 'रमज़ान उपवास ट्रैकर',
      'fasted_today': 'क्या आज उपवास है?',
      'fasting_completed': 'अल्हम्दुलिल्लाह, उपवास पूर्ण!',
      'fasting_not_completed': 'उपवास शुरू नहीं हुआ',
      'prayers_logged': 'लॉग की गई प्रार्थनाएँ',
      'mosques': 'आस-पास की मस्जिदें',
      'search_mosques': 'सुविधा द्वारा फ़िल्टर करें',
      'facility_women': 'महिला वर्ग',
      'facility_parking': 'पार्किंग क्षेत्र',
      'facility_jummah': 'एकाधिक जुम्मा पाली',
      'iqamah_time': 'इक़ामह',
      'suggest_iqamah': 'इक़ामह बदलाव का सुझाव दें',
      'get_directions': 'दिशा-निर्देश प्राप्त करें',
      'update_iqamah_title': 'इक़ामह समय का सुझाव दें',
      'update_success': 'इक़ामह समय सफलतापूर्वक अपडेट किया गया!',
      'enter_time': 'समय चुनें',
      'cancel': 'रद्द करें',
      'save': 'सहेजें',
      'distance': 'दूरी',
      'km': 'किमी',
      'method': 'गणना विधि',
      'next_prayer_in': 'अगली प्रार्थना में',
      'sehri_ends_in': 'सेहरी समाप्त होने में',
      'iftar_in': 'इफ्तार शुरू होने में',
      'offline_msg': 'ऑफ़लाइन मोड • स्थानीय कैश',
      'loading': 'प्रार्थना का समय अपडेट हो रहा है...',
      'bismillah': 'अल्लाह के नाम से, जो अत्यंत कृपालु और दयावान है',
      'change_lang': 'भाषा बदलें / Language',
      'active_lang': 'हिन्दी',
      'settings': 'सेटिंग्स और प्राथमिकताएं',
      'theme_mode': 'थीम मोड',
      'theme_system': 'सिस्टम डिफ़ॉल्ट',
      'theme_light': 'लाइट मोड',
      'theme_dark': 'डार्क मोड',
      'color_scheme': 'रंग योजना प्रीसेट',
      'color_emerald': 'पन्ना हरा (Emerald)',
      'color_sapphire': 'नीलम नीला (Sapphire)',
      'color_ruby': 'रूबी लाल (Ruby)',
      'profile': 'प्रोफ़ाइल और आँकड़े',
      'stats_weekly_prayers': 'साप्ताहिक प्रार्थनाएँ पूर्ण',
      'stats_weekly_fasts': 'लॉग किए गए उपवास (अंतिम 7 दिन)',
      'qaza_backlog': 'सक्रिय कज़ा बैकलॉग',
      'back_to_home': 'मुख्य पृष्ठ पर वापस',
      'active_preset': 'सक्रिय रंग थीम',
      'completed': 'पूर्ण',
      'days': 'दिन',
      'of_total': 'का',
      'exit_warning': 'बाहर निकलने के लिए फिर से वापस दबाएं',
      'current_prayer': 'वर्तमान प्रार्थना',
      'next_prayer': 'अगली प्रार्थना',
      'left': 'शेष',
      'time_elapsed': 'बीता हुआ',
      'remaining': 'बाकी',
      'quiz': 'क़ुरानिक क्विज़',
      'tafsir_review': 'तफ़सीर समीक्षा',
      'quiz_question_count': 'प्रश्न',
      'quiz_points': 'अंक',
      'quiz_next': 'अगला प्रश्न',
      'quiz_previous': 'पिछला',
      'quiz_finish': 'क्विज़ समाप्त करें',
      'quiz_lifetime_score': 'लाइफटाइम स्कोर',
      'quiz_completed_title': 'दैनिक क्विज़ पूरा हुआ!',
      'quiz_completed_sub': 'आपने आज के सभी 7 प्रश्नों के उत्तर दे दिए हैं। नई क़ुरानिक अंतर्दृष्टि के लिए कल फिर आएं!',
      'quiz_syncing': 'सर्वर के साथ सिंक हो रहा है...',
      'quiz_synced': 'प्रगति क्लाउड के साथ सुरक्षित रूप से सिंक हो गई है',
      'quiz_correct': 'सही',
      'quiz_incorrect': 'गलत',
      'quiz_tafsir_insight': 'तफ़सीर अंतर्दृष्टि',
      'quiz_pts': 'अंक',
      'no_questions_available': 'कोई प्रश्न उपलब्ध नहीं',
      'no_questions_available_sub': 'आज के लिए कोई प्रश्न कॉन्फ़िगर नहीं किया गया है। कृपया बाद में पुनः प्रयास करें।',
      'quiz_no_results': 'कोई परिणाम उपलब्ध नहीं है। कृपया पहले आज की प्रश्नोत्तरी पूरी करें।',
      'quiz_sync_error_timeout': 'कनेक्शन का समय समाप्त हो गया। प्रगति स्थानीय रूप से सहेजी गई।',
      'quiz_sync_error_failed': 'सिंक विफल रहा। प्रगति स्थानीय रूप से सहेजी गई।',
      'explore_tools': 'आध्यात्मिक हब',
      'hub_mosques_sub': 'आस-पास की मस्जिदें खोजें',
      'hub_quiz_sub': 'क़ुरानिक ज्ञान का परीक्षण करें',
      'hub_tracker_sub': 'दैनिक प्रार्थना लॉग करें',
      'hub_qaza_sub': 'छूटी हुई प्रार्थनाएँ ट्रैक करें',
      'hub_profile_sub': 'आंकड़े और लॉग देखें',
      'hub_settings_sub': 'थीम और गणना विधि',
      'special_timings': 'विशेष समय और वर्जित अवधियाँ',
      'forbidden_status': 'प्रार्थना अनुमति स्थिति',
      'prayer_allowed': 'सभी प्रार्थनाओं की अनुमति है',
      'prayer_forbidden': 'स्वैच्छिक प्रार्थनाएँ वर्जित हैं',
      'tahajjud_prayer': 'तहज्जुद प्रार्थना',
      'tahajjud_desc': 'रात्रि जागरण प्रार्थना',
      'tahajjud_best': 'तहज्जुद (सर्वोत्तम समय)',
      'ishraq_prayer': 'इशराक प्रार्थना',
      'ishraq_desc': 'सुबह की प्रार्थना',
      'forbidden_sunrise': 'सूर्योदय वर्जित अवधि',
      'forbidden_zawal': 'जवाल (मध्याह्न) वर्जित',
      'forbidden_sunset': 'सूर्यास्त वर्जित अवधि',
      'tahajjud_active': 'तहज्जुद का समय सक्रिय है',
      'ishraq_active': 'इशराक का समय सक्रिय है',
    },
    'ur': {
      'app_title': 'عدین • Adeen',
      'sehri': 'سحری کا اختتام',
      'iftar': 'افطار کا وقت',
      'fajr': 'فجر',
      'sunrise': 'طلوعِ آفتاب',
      'dhuhr': 'ظہر',
      'asr': 'عصر',
      'maghrib': 'مغرب',
      'isha': 'عشاء',
      'imsak': 'امساک',
      'prayer_tracker': 'نماز کا ٹریکر',
      'qaza_tracker': 'قضا نماز ٹریکر',
      'fasting_tracker': 'روزہ ٹریکر',
      'fasted_today': 'کیا آج روزہ ہے؟',
      'fasting_completed': 'الحمدللہ، روزہ مکمل!',
      'fasting_not_completed': 'روزہ شروع نہیں کیا گیا',
      'prayers_logged': 'اداکردہ نمازیں',
      'mosques': 'قریبی مساجد',
      'search_mosques': 'مساجد کی فلٹرنگ',
      'facility_women': 'خواتین کے لیے جگہ',
      'facility_parking': 'پارکنگ کی جگہ',
      'facility_jummah': 'متعدد نمازِ جمعہ',
      'iqamah_time': 'اقامت',
      'suggest_iqamah': 'اقامت کے وقت کی تجویز',
      'get_directions': 'راستہ معلوم کریں',
      'update_iqamah_title': 'اقامت کا وقت تجویز کریں',
      'update_success': 'اقامت کا وقت کامیابی سے تبدیل ہو گیا!',
      'enter_time': 'وقت منتخب کریں',
      'cancel': 'منسوخ کریں',
      'save': 'محفوظ کریں',
      'distance': 'فاصلہ',
      'km': 'کلومیٹر',
      'method': 'طریقہ کارِ حساب',
      'next_prayer_in': 'اگلی نماز میں وقت',
      'sehri_ends_in': 'سحری کے اختتام میں',
      'iftar_in': 'افطار کے وقت میں',
      'offline_msg': 'آف لائن موڈ • مقامی کیش',
      'loading': 'اوقاتِ نماز اپ ڈیٹ ہو رہے ہیں...',
      'bismillah': 'اللہ کے نام سے جو بڑا مہربان نہایت رحم والا ہے',
      'change_lang': 'زبان تبدیل کریں / Language',
      'active_lang': 'اردو',
      'settings': 'ترجیحات اور ترتیبات',
      'theme_mode': 'تھیم کا طریقہ کار',
      'theme_system': 'سسٹم ڈیفالٹ',
      'theme_light': 'لائٹ موڈ',
      'theme_dark': 'ڈارک موڈ',
      'color_scheme': 'رنگوں کی تھیم',
      'color_emerald': 'سبز زمرد',
      'color_sapphire': 'نیلم نیلا',
      'color_ruby': 'یاقوت سرخ',
      'profile': 'پروفائل اور اعداد و شمار',
      'stats_weekly_prayers': 'ہفتہ وار نمازیں مکمل',
      'stats_weekly_fasts': 'درج کردہ روزے (آخری 7 دن)',
      'qaza_backlog': 'بقیہ قضا نمازیں',
      'back_to_home': 'مرکزی صفحہ پر واپسی',
      'active_preset': 'سرگرم رنگوں کی تھیم',
      'completed': 'مکمل',
      'days': 'دن',
      'of_total': 'میں سے',
      'exit_warning': 'باہر نکلنے کے لیے دوبارہ دبائیں',
      'current_prayer': 'موجودہ نماز',
      'next_prayer': 'اگلی نماز',
      'left': 'باقی',
      'time_elapsed': 'گزر چکا',
      'remaining': 'باقی',
      'quiz': 'قرآنی کوئز',
      'tafsir_review': 'تفسیر کا جائزہ',
      'quiz_question_count': 'سوال',
      'quiz_points': 'پوائنٹس',
      'quiz_next': 'اگلا سوال',
      'quiz_previous': 'پچھلا',
      'quiz_finish': 'کوئز مکمل کریں',
      'quiz_lifetime_score': 'لائف ٹائم اسکور',
      'quiz_completed_title': 'روزانہ کوئز مکمل ہو گیا!',
      'quiz_completed_sub': 'آپ نے آج کے تمام 7 سوالات کے جوابات دے دیے ہیں۔ نئی قرآنی معلومات کے لیے کل دوبارہ تشریف لائیں!',
      'quiz_syncing': 'سرور کے ساتھ ہم آہنگ ہو رہا ہے...',
      'quiz_synced': 'پیش رفت محفوظ طریقے سے کلاؤڈ کے ساتھ ہم آہنگ ہو گئی ہے',
      'quiz_correct': 'درست',
      'quiz_incorrect': 'غلط',
      'quiz_tafsir_insight': 'تفسیر کی بصیرت',
      'quiz_pts': 'پوائنٹس',
      'no_questions_available': 'کوئی سوالات دستیاب نہیں ہیں',
      'no_questions_available_sub': 'آج کے لیے کوئی سوالات ترتیب نہیں دیے گئے ہیں۔ براہ کرم بعد میں دوبارہ کوشش کریں۔',
      'quiz_no_results': 'کوئی نتائج دستیاب نہیں ہیں۔ براہ کرم پہلے آج کا کوئز مکمل کریں۔',
      'quiz_sync_error_timeout': 'کنکشن کا وقت ختم ہو گیا۔ پیش رفت مقامی طور پر محفوظ کر لی گئی۔',
      'quiz_sync_error_failed': 'ہم آہنگی ناکام ہو گئی۔ پیش رفت مقامی طور پر محفوظ کر لی گئی۔',
      'explore_tools': 'روحانی مرکز',
      'hub_mosques_sub': 'قریبی مساجد تلاش کریں',
      'hub_quiz_sub': 'قرآنی معلومات کا امتحان لیں',
      'hub_tracker_sub': 'روزانہ کی نمازیں درج کریں',
      'hub_qaza_sub': 'قضا نمازوں کا حساب رکھیں',
      'hub_profile_sub': 'اعداد و شمار اور لاگ دیکھیں',
      'hub_settings_sub': 'تھیم اور حساب کتاب',
      'special_timings': 'خصوصی اوقات اور ممنوعہ اوقات',
      'forbidden_status': 'نماز کی اجازت کی صورتحال',
      'prayer_allowed': 'تمام نمازوں کی اجازت ہے',
      'prayer_forbidden': 'نفل نمازیں پڑھنا ممنوع ہے',
      'tahajjud_prayer': 'نمازِ تہجد',
      'tahajjud_desc': 'رات کی نماز',
      'tahajjud_best': 'تہجد (افضل وقت)',
      'ishraq_prayer': 'نمازِ اشراق',
      'ishraq_desc': 'صبح کی نماز',
      'forbidden_sunrise': 'طلوعِ آفتاب کا ممنوعہ وقت',
      'forbidden_zawal': 'زوال (دوپہر) کا ممنوعہ وقت',
      'forbidden_sunset': 'غروبِ آفتاب کا ممنوعہ وقت',
      'tahajjud_active': 'تہجد کا وقت شروع ہے',
      'ishraq_active': 'اشراق کا وقت شروع ہے',
    },
    'id': {
      'app_title': 'Adeen • عدين',
      'sehri': 'Sahur Berakhir',
      'iftar': 'Waktu Buka Puasa',
      'fajr': 'Subuh',
      'sunrise': 'Terbit Fajar',
      'dhuhr': 'Dzuhur',
      'asr': 'Ashar',
      'maghrib': 'Maghrib',
      'isha': 'Isya',
      'imsak': 'Imsak',
      'prayer_tracker': 'Pelacak Shalat Harian',
      'qaza_tracker': 'Pelacak Qadha',
      'fasting_tracker': 'Pelacak Puasa Ramadan',
      'fasted_today': 'Puasa Hari Ini?',
      'fasting_completed': 'Alhamdulillah, Puasa Selesai!',
      'fasting_not_completed': 'Puasa belum dimulai/dicatat',
      'prayers_logged': 'Shalat Dicatat',
      'mosques': 'Masjid Terdekat',
      'search_mosques': 'Filter Masjid',
      'facility_women': 'Ruang Wanita',
      'facility_parking': 'Tempat Parkir',
      'facility_jummah': 'Beberapa Gelombang Jumatan',
      'iqamah_time': 'Iqamah',
      'suggest_iqamah': 'Usulkan Waktu Iqamah',
      'get_directions': 'Petunjuk Arah',
      'update_iqamah_title': 'Usulkan Waktu Iqamah baru',
      'update_success': 'Waktu Iqamah berhasil diperbarui!',
      'enter_time': 'Pilih Waktu',
      'cancel': 'Batal',
      'save': 'Simpan',
      'distance': 'Jarak',
      'km': 'km',
      'method': 'Metode Perhitungan',
      'next_prayer_in': 'Shalat Berikutnya dalam',
      'sehri_ends_in': 'Sahur berakhir dalam',
      'iftar_in': 'Buka puasa dalam',
      'offline_msg': 'Mode Offline • Cache Lokal',
      'loading': 'Memperbarui jadwal shalat...',
      'bismillah': 'Dengan menyebut nama Allah Yang Maha Pengasih lagi Maha Penyayang',
      'change_lang': 'Ubah Bahasa / Language',
      'active_lang': 'Bahasa Indonesia',
      'settings': 'Pengaturan & Preferensi',
      'theme_mode': 'Mode Tema',
      'theme_system': 'Default Sistem',
      'theme_light': 'Mode Terang',
      'theme_dark': 'Mode Gelap',
      'color_scheme': 'Skema Warna Tema',
      'color_emerald': 'Hijau Zamrud',
      'color_sapphire': 'Biru Safir',
      'color_ruby': 'Merah Delima',
      'profile': 'Profil & Statistik',
      'stats_weekly_prayers': 'Shalat Mingguan Selesai',
      'stats_weekly_fasts': 'Puasa Dicatat (7 hari terakhir)',
      'qaza_backlog': 'Tunggakan Qadha Aktif',
      'back_to_home': 'Kembali ke Beranda',
      'active_preset': 'Tema Warna Aktif',
      'completed': 'selesai',
      'days': 'hari',
      'of_total': 'dari',
      'exit_warning': 'Tekan sekali lagi untuk keluar',
      'current_prayer': 'Shalat Sekarang',
      'next_prayer': 'Shalat Berikutnya',
      'left': 'tersisa',
      'time_elapsed': 'berlalu',
      'remaining': 'tersisa',
      'quiz': 'Kuis Al-Quran',
      'tafsir_review': 'Tinjauan Tafsir',
      'quiz_question_count': 'Pertanyaan',
      'quiz_points': 'Poin',
      'quiz_next': 'Pertanyaan Berikutnya',
      'quiz_previous': 'Sebelumnya',
      'quiz_finish': 'Selesaikan Kuis',
      'quiz_lifetime_score': 'Skor Seumur Hidup',
      'quiz_completed_title': 'Kuis Harian Selesai!',
      'quiz_completed_sub': 'Anda telah menjawab ke-7 pertanyaan hari ini. Kembali besok untuk wawasan Al-Quran baru!',
      'quiz_syncing': 'Menyinkronkan kemajuan dengan server...',
      'quiz_synced': 'Kemajuan berhasil disinkronkan ke cloud',
      'quiz_correct': 'Benar',
      'quiz_incorrect': 'Salah',
      'quiz_tafsir_insight': 'Wawasan Tafsir',
      'quiz_pts': 'poin',
      'no_questions_available': 'Tidak Ada Pertanyaan',
      'no_questions_available_sub': 'Tidak ada pertanyaan untuk hari ini. Silakan coba lagi nanti.',
      'quiz_no_results': 'Tidak ada hasil. Harap selesaikan kuis hari ini terlebih dahulu.',
      'quiz_sync_error_timeout': 'Koneksi habis waktu. Kemajuan disimpan secara lokal.',
      'quiz_sync_error_failed': 'Sinkronisasi gagal. Kemajuan disimpan secara lokal.',
      'explore_tools': 'Hub Spiritual',
      'hub_mosques_sub': 'Cari masjid terdekat',
      'hub_quiz_sub': 'Uji wawasan Al-Quran',
      'hub_tracker_sub': 'Catat shalat harian',
      'hub_qaza_sub': 'Lacak tunggakan qadha',
      'hub_profile_sub': 'Lihat statistik & catatan',
      'hub_settings_sub': 'Tema & perhitungan',
      'special_timings': 'Waktu Khusus & Periode Dilarang',
      'forbidden_status': 'Status Izin Shalat',
      'prayer_allowed': 'Semua shalat diperbolehkan',
      'prayer_forbidden': 'Shalat sunnah dilarang',
      'tahajjud_prayer': 'Shalat Tahajjud',
      'tahajjud_desc': 'Shalat malam hari',
      'tahajjud_best': 'Tahajjud (Waktu Terbaik)',
      'ishraq_prayer': 'Shalat Ishraq',
      'ishraq_desc': 'Shalat awal pagi',
      'forbidden_sunrise': 'Waktu Dilarang (Terbit Matahari)',
      'forbidden_zawal': 'Waktu Dilarang (Zawal / Tengah Hari)',
      'forbidden_sunset': 'Waktu Dilarang (Jelang Maghrib)',
      'tahajjud_active': 'Waktu Tahajjud Aktif',
      'ishraq_active': 'Waktu Ishraq Aktif',
    },
    'ms': {
      'app_title': 'Adeen • عدين',
      'sehri': 'Sahur Tamat',
      'iftar': 'Waktu Berbuka',
      'fajr': 'Subuh',
      'sunrise': 'Syuruk',
      'dhuhr': 'Zohor',
      'asr': 'Asar',
      'maghrib': 'Maghrib',
      'isha': 'Isyak',
      'imsak': 'Imsak',
      'prayer_tracker': 'Pelacak Solat Harian',
      'qaza_tracker': 'Pelacak Qadha',
      'fasting_tracker': 'Pelacak Puasa Ramadan',
      'fasted_today': 'Puasa Hari Ini?',
      'fasting_completed': 'Alhamdulillah, Puasa Selesai!',
      'fasting_not_completed': 'Puasa belum dimulakan/dicatat',
      'prayers_logged': 'Solat Dicatat',
      'mosques': 'Masjid Berdekatan',
      'search_mosques': 'Tapis Masjid',
      'facility_women': 'Ruang Wanita',
      'facility_parking': 'Kawasan Parkir',
      'facility_jummah': 'Beberapa Gelombang Solat Jumaat',
      'iqamah_time': 'Iqamah',
      'suggest_iqamah': 'Cadangkan Waktu Iqamah',
      'get_directions': 'Petunjuk Arah',
      'update_iqamah_title': 'Cadangkan Waktu Iqamah baru',
      'update_success': 'Waktu Iqamah berjaya dikemaskini!',
      'enter_time': 'Pilih Waktu',
      'cancel': 'Batal',
      'save': 'Simpan',
      'distance': 'Jarak',
      'km': 'km',
      'method': 'Kaedah Pengiraan',
      'next_prayer_in': 'Solat Seterusnya dalam',
      'sehri_ends_in': 'Sahur tamat dalam',
      'iftar_in': 'Berbuka puasa dalam',
      'offline_msg': 'Mod Luar Talian • Cache Tempatan',
      'loading': 'Mengemas kini jadual solat...',
      'bismillah': 'Dengan nama Allah Yang Maha Pemurah lagi Maha Penyayang',
      'change_lang': 'Tukar Bahasa / Language',
      'active_lang': 'Bahasa Melayu',
      'settings': 'Tetapan & Keutamaan',
      'theme_mode': 'Mod Tema',
      'theme_system': 'Default Sistem',
      'theme_light': 'Mod Cerah',
      'theme_dark': 'Mod Gelap',
      'color_scheme': 'Skema Warna Tema',
      'color_emerald': 'Hijau Zamrud',
      'color_sapphire': 'Biru Nilam',
      'color_ruby': 'Merah Delima',
      'profile': 'Profil & Statistik',
      'stats_weekly_prayers': 'Solat Mingguan Selesai',
      'stats_weekly_fasts': 'Puasa Dicatat (7 hari terakhir)',
      'qaza_backlog': 'Tunggakan Qadha Aktif',
      'back_to_home': 'Kembali ke Laman Utama',
      'active_preset': 'Tema Warna Aktif',
      'completed': 'selesai',
      'days': 'hari',
      'of_total': 'daripada',
      'exit_warning': 'Tekan sekali lagi untuk keluar',
      'current_prayer': 'Solat Sekarang',
      'next_prayer': 'Solat Seterusnya',
      'left': 'tinggal',
      'time_elapsed': 'berlalu',
      'remaining': 'tinggal',
      'quiz': 'Kuiz Al-Quran',
      'tafsir_review': 'Tinjauan Tafsir',
      'quiz_question_count': 'Soalan',
      'quiz_points': 'Mata',
      'quiz_next': 'Soalan Seterusnya',
      'quiz_previous': 'Sebelumnya',
      'quiz_finish': 'Selesaikan Kuiz',
      'quiz_lifetime_score': 'Skor Sepanjang Hayat',
      'quiz_completed_title': 'Kuiz Harian Selesai!',
      'quiz_completed_sub': 'Anda telah menjawab semua 7 soalan untuk hari ini. Kembali esok untuk wawasan Al-Quran yang baru!',
      'quiz_syncing': 'Menyinkronkan kemajuan dengan pelayan...',
      'quiz_synced': 'Kemajuan berjaya disinkronkan ke awan',
      'quiz_correct': 'Betul',
      'quiz_incorrect': 'Salah',
      'quiz_tafsir_insight': 'Wawasan Tafsir',
      'quiz_pts': 'mata',
      'no_questions_available': 'Tiada Soalan Tersedia',
      'no_questions_available_sub': 'Tiada soalan dikonfigurasikan untuk hari ini. Sila cuba lagi kemudian.',
      'quiz_no_results': 'Tiada keputusan tersedia. Sila selesaikan kuiz hari ini terlebih dahulu.',
      'quiz_sync_error_timeout': 'Sambungan tamat masa. Kemajuan disimpan secara tempatan.',
      'quiz_sync_error_failed': 'Penyinkronan gagal. Kemajuan disimpan secara tempatan.',
      'explore_tools': 'Hub Spiritual',
      'hub_mosques_sub': 'Cari masjid berdekatan',
      'hub_quiz_sub': 'Uji wawasan Al-Quran',
      'hub_tracker_sub': 'Catat solat harian',
      'hub_qaza_sub': 'Jejak tunggakan qada',
      'hub_profile_sub': 'Lihat statistik & rekod',
      'hub_settings_sub': 'Tema & pengiraan',
      'special_timings': 'Waktu Khas & Tempoh Dilarang',
      'forbidden_status': 'Status Keizinan Solat',
      'prayer_allowed': 'Semua solat dibenarkan',
      'prayer_forbidden': 'Solat sunat dilarang',
      'tahajjud_prayer': 'Solat Tahajjud',
      'tahajjud_desc': 'Solat malam hari',
      'tahajjud_best': 'Tahajjud (Waktu Terbaik)',
      'ishraq_prayer': 'Solat Isyraq',
      'ishraq_desc': 'Solat awal pagi',
      'forbidden_sunrise': 'Tempoh Dilarang (Syuruk)',
      'forbidden_zawal': 'Tempoh Dilarang (Zawal / Tengah Hari)',
      'forbidden_sunset': 'Tempoh Dilarang (Jelang Maghrib)',
      'tahajjud_active': 'Waktu Tahajjud Aktif',
      'ishraq_active': 'Waktu Isyraq Aktif',
    },
    'tr': {
      'app_title': 'Adeen • عدين',
      'sehri': 'Sahur Bitiş',
      'iftar': 'İftar Vakti',
      'fajr': 'İmsak / Sabah',
      'sunrise': 'Güneş',
      'dhuhr': 'Öğle',
      'asr': 'İkindi',
      'maghrib': 'Akşam',
      'isha': 'Yatsı',
      'imsak': 'İmsak',
      'prayer_tracker': 'Günlük Namaz Takipçisi',
      'qaza_tracker': 'Kaza Namazı Takibi',
      'fasting_tracker': 'Ramazan Oruç Takipçisi',
      'fasted_today': 'Bugün Oruçlu musunuz?',
      'fasting_completed': 'Alhamdülillah, Oruç Tamamlandı!',
      'fasting_not_completed': 'Oruç henüz kaydedilmedi',
      'prayers_logged': 'Kaydedilen Namazlar',
      'mosques': 'Yakındaki Camiler',
      'search_mosques': 'Cami Özellik Filtresi',
      'facility_women': 'Kadınlar Bölümü',
      'facility_parking': 'Otopark Alanı',
      'facility_jummah': 'Çoklu Cuma Namazı',
      'iqamah_time': 'Kamet',
      'suggest_iqamah': 'Kamet Vakti Öner',
      'get_directions': 'Yol Tarifi Al',
      'update_iqamah_title': 'Kamet Vakti Öner',
      'update_success': 'Kamet vakti başarıyla güncellendi!',
      'enter_time': 'Saat Seç',
      'cancel': 'İptal',
      'save': 'Kaydet',
      'distance': 'Mesafe',
      'km': 'km',
      'method': 'Hesaplama Yöntemi',
      'next_prayer_in': 'Sıradaki Ezan',
      'sehri_ends_in': 'Sahur bitimine kalan',
      'iftar_in': 'İftara kalan süre',
      'offline_msg': 'Çevrimdışı Mod • Yerel Önbellek',
      'loading': 'Namaz vakitleri güncelleniyor...',
      'bismillah': 'Rahman ve Rahim olan Allah\'ın adıyla',
      'change_lang': 'Dili Değiştir / Language',
      'active_lang': 'Türkçe',
      'settings': 'Ayarlar ve Tercihler',
      'theme_mode': 'Tema Modu',
      'theme_system': 'Sistem Varsayılanı',
      'theme_light': 'Açık Tema',
      'theme_dark': 'Karanlık Tema',
      'color_scheme': 'Renk Teması Önayarı',
      'color_emerald': 'Zümrüt Yeşili',
      'color_sapphire': 'Safir Mavisi',
      'color_ruby': 'Yakut Kırmızısı',
      'profile': 'Profil & İstatistikler',
      'stats_weekly_prayers': 'Haftalık Kılınan Namazlar',
      'stats_weekly_fasts': 'Tutulan Oruçlar (Son 7 gün)',
      'qaza_backlog': 'Kaza Namazı Borcu',
      'back_to_home': 'Ana Sayfaya Dön',
      'active_preset': 'Aktif Renk Teması',
      'completed': 'tamamlandı',
      'days': 'gün',
      'of_total': '/',
      'exit_warning': 'Çıkmak için tekrar geri basın',
      'current_prayer': 'Mevcut Namaz',
      'next_prayer': 'Sıradaki Namaz',
      'left': 'kaldı',
      'time_elapsed': 'geçen',
      'remaining': 'kalan',
      'quiz': 'Kuran Bilgi Yarışması',
      'tafsir_review': 'Tefsir İncelemesi',
      'quiz_question_count': 'Soru',
      'quiz_points': 'Puan',
      'quiz_next': 'Sonraki Soru',
      'quiz_previous': 'Önceki',
      'quiz_finish': 'Yarışmayı Bitir',
      'quiz_lifetime_score': 'Toplam Puan',
      'quiz_completed_title': 'Günlük Yarışma Tamamlandı!',
      'quiz_completed_sub': 'Bugünün 7 sorusunun tamamını cevapladınız. Yeni Kuran bilgileri için yarın tekrar gelin!',
      'quiz_syncing': 'İlerleme sunucuyla eşitleniyor...',
      'quiz_synced': 'İlerleme bulutla güvenli bir şekilde eşitlendi',
      'quiz_correct': 'Doğru',
      'quiz_incorrect': 'Yanlış',
      'quiz_tafsir_insight': 'Tefsir Analizi',
      'quiz_pts': 'puan',
      'no_questions_available': 'Kullanılabilir Soru Yok',
      'no_questions_available_sub': 'Bugün için yapılandırılmış soru yok. Lütfen daha sonra tekrar deneyin.',
      'quiz_no_results': 'Kullanılabilir sonuç yok. Lütfen önce bugünün yarışmasını tamamlayın.',
      'quiz_sync_error_timeout': 'Bağlantı zaman aşımına uğradı. İlerleme yerel olarak kaydedildi.',
      'quiz_sync_error_failed': 'Eşitleme başarısız oldu. İlerleme yerel olarak kaydedildi.',
      'explore_tools': 'Manevi Merkez',
      'hub_mosques_sub': 'Yakındaki camileri bul',
      'hub_quiz_sub': 'Kuran bilgisini test et',
      'hub_tracker_sub': 'Günlük namazları kaydet',
      'hub_qaza_sub': 'Kaza namazlarını takip et',
      'hub_profile_sub': 'İstatistikleri ve günlüğü gör',
      'hub_settings_sub': 'Temalar ve hesaplama',
      'special_timings': 'Özel Vakitler ve Kerahat Vakitleri',
      'forbidden_status': 'Namaz Kılma Durumu',
      'prayer_allowed': 'Tüm namazlar kılınabilir',
      'prayer_forbidden': 'Nafile namaz kılmak mekruhtur',
      'tahajjud_prayer': 'Teheccüd Namazı',
      'tahajjud_desc': 'Gece namazı',
      'tahajjud_best': 'Teheccüd (En Faziletli Vakit)',
      'ishraq_prayer': 'İşrak Namazı',
      'ishraq_desc': 'Kuşluk öncesi namaz',
      'forbidden_sunrise': 'Güneş Doğarken Kerahat Vakti',
      'forbidden_zawal': 'Öğle Öncesi Kerahat Vakti (Zeval)',
      'forbidden_sunset': 'Akşam Öncesi Kerahat Vakti (Grup)',
      'tahajjud_active': 'Teheccüd Vakti Girdi',
      'ishraq_active': 'İşrak Vakti Girdi',
    },
    'fr': {
      'app_title': 'Adeen • عدين',
      'sehri': 'Fin du Sehri',
      'iftar': 'Heure de l\'Iftar',
      'fajr': 'Fajr',
      'sunrise': 'Lever du soleil',
      'dhuhr': 'Dhuhr',
      'asr': 'Asr',
      'maghrib': 'Maghrib',
      'isha': 'Isha',
      'imsak': 'Imsak',
      'prayer_tracker': 'Suivi des prières',
      'qaza_tracker': 'Suivi des prières Qaza',
      'fasting_tracker': 'Suivi du Jeûne du Ramadan',
      'fasted_today': 'Jeûnez-vous aujourd\'hui ?',
      'fasting_completed': 'Alhamdulillah, Jeûne Complété !',
      'fasting_not_completed': 'Jeûne non commencé/enregistré',
      'prayers_logged': 'Prières Enregistrées',
      'mosques': 'Mosquées à proximité',
      'search_mosques': 'Filtrer les mosquées',
      'facility_women': 'Espace femmes',
      'facility_parking': 'Parking disponible',
      'facility_jummah': 'Plusieurs prières du Vendredi',
      'iqamah_time': 'Iqamah',
      'suggest_iqamah': 'Suggérer une heure d\'Iqamah',
      'get_directions': 'Itinéraire',
      'update_iqamah_title': 'Suggérer l\'Iqamah',
      'update_success': 'Heure de l\'Iqamah mise à jour !',
      'enter_time': 'Sélectionner l\'heure',
      'cancel': 'Annuler',
      'save': 'Enregistrer',
      'distance': 'Distance',
      'km': 'km',
      'method': 'Méthode de calcul',
      'next_prayer_in': 'Prochaine prière dans',
      'sehri_ends_in': 'Fin du sahur dans',
      'iftar_in': 'Iftar dans',
      'offline_msg': 'Mode Hors-ligne • Cache Local',
      'loading': 'Mise à jour des horaires...',
      'bismillah': 'Au nom d\'Allah, le Tout Miséricordieux, le Très Miséricordieux',
      'change_lang': 'Changer de Langue / Language',
      'active_lang': 'Français',
      'settings': 'Paramètres & Préférences',
      'theme_mode': 'Mode Thème',
      'theme_system': 'Défaut Système',
      'theme_light': 'Mode Clair',
      'theme_dark': 'Mode Sombre',
      'color_scheme': 'Palette de Couleurs',
      'color_emerald': 'Vert Émeraude',
      'color_sapphire': 'Bleu Saphir',
      'color_ruby': 'Rouge Rubis',
      'profile': 'Profil & Statistiques',
      'stats_weekly_prayers': 'Prières hebdomadaires complétées',
      'stats_weekly_fasts': 'Jeûnes enregistrés (7 derniers jours)',
      'qaza_backlog': 'Prières Qaza en retard',
      'back_to_home': 'Retour à l\'accueil',
      'active_preset': 'Thème de couleur actif',
      'completed': 'complétée(s)',
      'days': 'jours',
      'of_total': 'sur',
      'exit_warning': 'Appuyez à nouveau pour quitter',
      'current_prayer': 'Prière Actuelle',
      'next_prayer': 'Prochaine Prière',
      'left': 'restant',
      'time_elapsed': 'écoulé',
      'remaining': 'restant',
      'quiz': 'Quiz Coranique',
      'tafsir_review': 'Revue de Tafsir',
      'quiz_question_count': 'Question',
      'quiz_points': 'Points',
      'quiz_next': 'Question Suivante',
      'quiz_previous': 'Précédent',
      'quiz_finish': 'Terminer le Quiz',
      'quiz_lifetime_score': 'Score Total',
      'quiz_completed_title': 'Quiz Quotidien Terminé !',
      'quiz_completed_sub': 'Vous avez répondu aux 7 questions du jour. Revenez demain pour de nouvelles analyses coraniques !',
      'quiz_syncing': 'Synchronisation de la progression...',
      'quiz_synced': 'Progression synchronisée sur le cloud',
      'quiz_correct': 'Correct',
      'quiz_incorrect': 'Incorrect',
      'quiz_tafsir_insight': 'Aperçu du Tafsir',
      'quiz_pts': 'pts',
      'no_questions_available': 'Aucune question disponible',
      'no_questions_available_sub': 'Aucune question n\'est configurée pour aujourd\'hui. Veuillez réessayer plus tard.',
      'quiz_no_results': 'Aucun résultat disponible. Veuillez d\'abord terminer le quiz d\'aujourd\'hui.',
      'quiz_sync_error_timeout': 'Délai de connexion dépassé. Progression enregistrée localement.',
      'quiz_sync_error_failed': 'Échec de la synchronisation. Progression enregistrée localement.',
      'explore_tools': 'Hub Spirituel',
      'hub_mosques_sub': 'Trouver les mosquées',
      'hub_quiz_sub': 'Tester vos connaissances',
      'hub_tracker_sub': 'Enregistrer les prières',
      'hub_qaza_sub': 'Suivre les prières manquées',
      'hub_profile_sub': 'Statistiques & historique',
      'hub_settings_sub': 'Thèmes & calculs',
      'special_timings': 'Horaires Spéciaux & Périodes Interdites',
      'forbidden_status': 'Statut d\'autorisation de prière',
      'prayer_allowed': 'Toutes les prières sont autorisées',
      'prayer_forbidden': 'Prières volontaires interdites',
      'tahajjud_prayer': 'Prière du Tahajjud',
      'tahajjud_desc': 'Prière nocturne',
      'tahajjud_best': 'Tahajjud (Meilleur Moment)',
      'ishraq_prayer': 'Prière de l\'Ishraq',
      'ishraq_desc': 'Prière après le lever du soleil',
      'forbidden_sunrise': 'Période interdite (Lever du soleil)',
      'forbidden_zawal': 'Période interdite (Zenith)',
      'forbidden_sunset': 'Période interdite (Coucher du soleil)',
      'tahajjud_active': 'Le temps du Tahajjud est actif',
      'ishraq_active': 'Le temps de l\'Ishraq est actif',
    }
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  bool get isRTL => locale.languageCode == 'ar' || locale.languageCode == 'ur';
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => [
        'en',
        'ar',
        'bn',
        'hi',
        'ur',
        'id',
        'ms',
        'tr',
        'fr',
      ].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
