import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const _localizedValues = {
    'en': {
      'app_title': 'Adeen • عدين',
      'sehri': 'Sehri Ends',
      'iftar': 'Iftar Time',
      'fajr': 'Fajr',
      'sunrise': 'Sunrise',
      'dhuhr': 'Dhuhr',
      'jumah_prayer': 'Jumah',
      'asr': 'Asr',
      'maghrib': 'Maghrib',
      'isha': 'Isha',
      'imsak': 'Imsak',
      'prayer_tracker': 'Daily Prayers Tracker',
      'qaza_tracker': 'Qaza Tracker',
      'fasting_tracker': 'Ramadan Fasting Tracker',
      'fasted_today': 'Fasting Today?',
      'fasting_completed': 'Alhamdulillah, Fast Completed!',
      'fasting_not_completed': 'Fast not started/logged yet',
      'prayers_logged': 'Prayers Logged',
      'mosques': 'Nearby Mosques',
      'mosque_data_disclaimer': 'Note: Mosque details and locations are retrieved from Google Maps and may not be fully accurate.',
      'search_mosques': 'Filter Mosques by Facility',
      'facility_women': 'Women\'s Section',
      'facility_parking': 'Parking Space',
      'facility_jummah': 'Multiple Jummah Shifts',
      'iqamah_time': 'Iqamah',
      'suggest_iqamah': 'Suggest Iqamah Update',
      'get_directions': 'Get Directions',
      'update_iqamah_title': 'Suggest Iqamah Time',
      'update_success': 'Iqamah time updated successfully!',
      'enter_time': 'Select Time',
      'cancel': 'Cancel',
      'change': 'Change',
      'today_prayers': 'Today\'s Prayers',
      'hijri_month_1': 'Muharram',
      'hijri_month_2': 'Safar',
      'hijri_month_3': 'Rabi\' I',
      'hijri_month_4': 'Rabi\' II',
      'hijri_month_5': 'Jumada I',
      'hijri_month_6': 'Jumada II',
      'hijri_month_7': 'Rajab',
      'hijri_month_8': 'Sha\'ban',
      'hijri_month_9': 'Ramadan',
      'hijri_month_10': 'Shawwal',
      'hijri_month_11': 'Dhu al-Qi\'dah',
      'hijri_month_12': 'Dhu al-Hijjah',
      'save': 'Save',
      'distance': 'Distance',
      'km': 'km',
      'method': 'Calculation Method',
      'calculation_settings': 'Calculation Settings',
      'method_karachi': 'University of Islamic Sciences, Karachi',
      'method_isna': 'Islamic Society of North America (ISNA)',
      'method_mwl': 'Muslim World League (MWL)',
      'method_umm_al_qura': 'Umm Al-Qura University, Makkah',
      'method_egyptian': 'Egyptian General Authority of Survey',
      'method_gulf': 'Gulf Region',
      'method_kuwait': 'Kuwait',
      'method_qatar': 'Qatar',
      'method_singapore': 'MUIS (Singapore)',
      'method_turkey': 'Diyanet (Turkey)',
      'method_jafari': 'Shia Ithna-Ashari, Leva Institute, Qum',
      'method_tehran': 'Institute of Geophysics, Univ. of Tehran',
      'method_france': 'Union Organization Islamic de France',
      'method_russia': 'Spiritual Administration of Muslims of Russia',
      'method_moonsighting': 'Moonsighting Committee Worldwide',
      'method_dubai': 'Dubai (Experimental)',
      'method_jakim': 'JAKIM, Malaysia',
      'method_tunisia': 'Tunisia',
      'method_algeria': 'Algeria',
      'method_kemenag': 'Kemenag (Indonesia)',
      'method_morocco': 'Morocco',
      'method_portugal': 'Comunidade Islamica de Lisboa, Portugal',
      'method_jordan': 'Ministry of Awqaf, Jordan',
      'juristic_method': 'Juristic Method (School)',
      'school_standard': 'Standard (Shafi\'i, Maliki, Hanbali)',
      'school_hanafi': 'Hanafi',
      'next_prayer_in': 'Next Prayer in',
      'sehri_ends_in': 'Sehri ends in',
      'iftar_in': 'Iftar starts in',
      'offline_msg': 'Offline Mode • Local Cache',
      'loading': 'Updating prayer times...',
      'bismillah': 'In the name of Allah, the Beneficent, the Merciful',
      'change_lang': 'Language / ভাষা / اللغة',
      'active_lang': 'English',
      'settings': 'Settings & Preferences',
      'home': 'Home',
      'theme_mode': 'Theme Mode',
      'theme_system': 'System Default',
      'theme_light': 'Light Mode',
      'theme_dark': 'Dark Mode',
      'color_scheme': 'Color Preset Schema',
      'color_emerald': 'Emerald Green',
      'color_sapphire': 'Sapphire Blue',
      'color_ruby': 'Ruby Red',
      'profile': 'User Profile & Statistics',
      'stats_weekly_prayers': 'Weekly Prayers Completed',
      'stats_weekly_fasts': 'Fasts Logged (Last 7 days)',
      'qaza_backlog': 'Active Qaza Backlog',
      'back_to_home': 'Back to Home',
      'active_preset': 'Active Color Theme',
      'completed': 'completed',
      'days': 'days',
      'of_total': 'of',
      'exit_warning': 'Press back again to exit',
      'current_prayer': 'Current Prayer',
      'next_prayer': 'Next Prayer',
      'left': 'left',
      'time_elapsed': 'elapsed',
      'remaining': 'remaining',
      'quiz': 'Quranic Quiz',
      'tafsir_review': 'Tafsir Review',
      'quiz_question_count': 'Question',
      'quiz_points': 'Points',
      'quiz_next': 'Next Question',
      'quiz_previous': 'Previous',
      'quiz_finish': 'Finish Quiz',
      'quiz_lifetime_score': 'Lifetime Score',
      'quiz_completed_title': 'Daily Quiz Completed!',
      'quiz_completed_sub': 'You have answered all 7 questions for today. Come back tomorrow for a new set of Quranic insights!',
      'quiz_syncing': 'Syncing progress with server...',
      'quiz_synced': 'Progress securely synced to cloud',
      'quiz_correct': 'Correct',
      'quiz_incorrect': 'Incorrect',
      'quiz_tafsir_insight': 'Tafsir Insight',
      'quiz_pts': 'pts',
      'no_questions_available': 'No Questions Available',
      'no_questions_available_sub': 'There are no questions configured for today. Please try again later.',
      'quiz_no_results': "No results available. Please complete today's quiz first.",
      'quiz_sync_error_timeout': 'Connection timed out. Progress saved locally.',
      'quiz_sync_error_failed': 'Sync failed. Progress saved locally.',
      'explore_tools': 'Spiritual Hub',
      'hub_mosques_sub': 'Find nearby mosques',
      'hub_quiz_sub': 'Test Quranic insights',
      'hub_tracker_sub': 'Log daily prayers',
      'hub_qaza_sub': 'Track missed prayers',
      'hub_profile_sub': 'View stats & log',
      'hub_settings_sub': 'Themes & calculation',
      'qibla_finder': 'Qibla Finder',
      'hub_qibla_sub': 'Find the direction of Mecca',
      'qibla_direction': 'Qibla Direction',
      'qibla_searching': 'Determining location…',
      'qibla_error': 'Unable to determine Qibla direction. Please enable location access.',
      'qibla_sensor_unavailable': 'Compass sensor not available on this device.',
      'special_timings': 'Prohibited Periods',
      'view_calendar': 'Prayer Timetable Calendar',
      'calendar_subtitle': 'See weekly, monthly & custom date timings',
      'tab_week': 'Weekly',
      'tab_month': 'Monthly',
      'tab_date': 'Select Date',
      'tap_view_details': 'Tap to view details',
      'no_timings_found': 'No timings found',
      'forbidden_status': 'Prayer Permission Status',
      'prayer_allowed': 'Prayers are permitted',
      'prayer_forbidden': 'Voluntary prayers are prohibited',
      'tahajjud_prayer': 'Tahajjud Prayer',
      'tahajjud_desc': 'Night vigil prayer',
      'tahajjud_best': 'Tahajjud (Best Time)',
      'ishraq_prayer': 'Ishraq Prayer',
      'chasht_duha': 'Chasht (Duha)',
      'chasht_desc': 'Forenoon voluntary prayer',
      'chasht_info_title': 'About Chasht (Duha) Prayer',
      'chasht_info_body': 'Chasht (or Duha) is a voluntary prayer performed when the sun is high in the sky. Its window starts 45 minutes after sunrise and ends 10 minutes before Dhuhr. It is a highly recommended Sunnah that brings abundance and acts as charity for the joints.',
      'ishraq_desc': 'Early morning prayer',
      'forbidden_sunrise': 'Sunrise Forbidden Period',
      'forbidden_zawal': 'Zawal (Midday) Forbidden',
      'forbidden_sunset': 'Sunset Forbidden Period',
      'forbidden_time': 'Forbidden Time',
      'prayer_not_permitted': 'Prayer is not permitted',
      'tahajjud_active': 'Tahajjud Time is Active',
      'state_active': 'Present',
      'state_upcoming': 'Upcoming',
      'ishraq_active': 'Ishraq Time is Active',
      'chasht_duha_active': 'Chasht (Duha) is Active',
      'select_language': 'Select Language',
      'confirm': 'Confirm',
      'lang_detect_desc': 'We detected your language based on your location. Feel free to change it.',
      'tahajjud_info_title': 'About Tahajjud Prayer',
      'tahajjud_info_body': 'Tahajjud is a voluntary night prayer performed after waking up from sleep. Its window is from Isha until Fajr, with the best time being the last third of the night. It is a highly recommended Sunnah that brings spiritual elevation, forgiveness, and peace.',
      'ishraq_info_title': 'About Ishraq (Duha) Prayer',
      'ishraq_info_body': 'Ishraq (also known as the beginning of Duha) is a voluntary morning prayer. Its window starts 15 minutes after sunrise and ends 10 minutes before Dhuhr. Praying it (especially after remembering Allah in place after Fajr) brings immense blessings.',
      'close': 'Close',
      'am': 'AM',
      'pm': 'PM',
      'ishraq': 'Ishraq',
    },
    'ar': {
      'app_title': 'عدين • Adeen',
      'sehri': 'نهاية السحور',
      'iftar': 'وقت الإفطار',
      'fajr': 'الفجر',
      'sunrise': 'الشروق',
      'dhuhr': 'الظهر',
      'jumah_prayer': 'الجمعة',
      'asr': 'العصر',
      'maghrib': 'المغرب',
      'isha': 'العشاء',
      'imsak': 'الإمساك',
      'prayer_tracker': 'مصحح الصلوات اليومية',
      'qaza_tracker': 'متابعة صلوات القضاء',
      'fasting_tracker': 'متابعة الصيام الرمضاني',
      'fasted_today': 'صائم اليوم؟',
      'fasting_completed': 'الحمد لله، تم الصيام!',
      'fasting_not_completed': 'لم يبدأ الصوم/لم يسجل بعد',
      'prayers_logged': 'الصلوات المسجلة',
      'mosques': 'المساجد القريبة',
      'mosque_data_disclaimer': 'ملاحظة: يتم الحصول على تفاصيل ومواقع المساجد من خرائط Google وقد لا تكون دقيقة تمامًا.',
      'search_mosques': 'تصفية المساجد حسب المرافق',
      'facility_women': 'مصلى للنساء',
      'facility_parking': 'مواقف سيارات',
      'facility_jummah': 'خطب جمعة متعددة',
      'iqamah_time': 'الإقامة',
      'suggest_iqamah': 'اقتراح تعديل وقت الإقامة',
      'get_directions': 'الحصول على الاتجاهات',
      'update_iqamah_title': 'اقتراح وقت الإقامة',
      'update_success': 'تم تحديث وقت الإقامة بنجاح!',
      'enter_time': 'اختر الوقت',
      'cancel': 'إلغاء',
      'change': 'تغيير',
      'today_prayers': 'صلوات اليوم',
      'hijri_month_1': 'المحرم',
      'hijri_month_2': 'صفر',
      'hijri_month_3': 'ربيع الأول',
      'hijri_month_4': 'ربيع الثاني',
      'hijri_month_5': 'جمادى الأولى',
      'hijri_month_6': 'جمادى الآخرة',
      'hijri_month_7': 'رجب',
      'hijri_month_8': 'شعبان',
      'hijri_month_9': 'رمضان',
      'hijri_month_10': 'شوال',
      'hijri_month_11': 'ذو القعدة',
      'hijri_month_12': 'ذو الحجة',
      'save': 'حفظ',
      'distance': 'المسافة',
      'km': 'كم',
      'method': 'طريقة الحساب',
      'calculation_settings': 'إعدادات الحساب',
      'method_karachi': 'جامعة العلوم الإسلامية بكراتشي',
      'method_isna': 'الجمعية الإسلامية لأمريكا الشمالية (ISNA)',
      'method_mwl': 'رابطة العالم الإسلامي',
      'method_umm_al_qura': 'جامعة أم القرى، مكة المكرمة',
      'method_egyptian': 'الهيئة المصرية العامة للمساحة',
      'method_gulf': 'منطقة الخليج',
      'method_kuwait': 'الكويت',
      'method_qatar': 'قطر',
      'method_singapore': 'المجلس الإسلامي السنغافوري (MUIS)',
      'method_turkey': 'رئاسة الشؤون الدينية التركية (ديانت)',
      'method_jafari': 'معهد ليفا، قم (جعفري)',
      'method_tehran': 'معهد الجيوفيزياء، جامعة طهران',
      'method_france': 'الاتحاد الإسلامي في فرنسا (UOIF)',
      'method_russia': 'الإدارة الدينية لمسلمي روسيا',
      'method_moonsighting': 'لجنة رؤية الهلال العالمية',
      'method_dubai': 'دبي (تجريبي)',
      'method_jakim': 'JAKIM، ماليزيا',
      'method_tunisia': 'تونس',
      'method_algeria': 'الجزائر',
      'method_kemenag': 'كيمناغ (إندونيسيا)',
      'method_morocco': 'المغرب',
      'method_portugal': 'الجماعة الإسلامية في لشبونة، البرتغال',
      'method_jordan': 'وزارة الأوقاف، الأردن',
      'juristic_method': 'المذهب الفقهي (العصر)',
      'school_standard': 'الجمهور (شافعي، مالكي، حنبلي)',
      'school_hanafi': 'حنفي',
      'next_prayer_in': 'الصلاة القادمة خلال',
      'sehri_ends_in': 'ينتهي السحور خلال',
      'iftar_in': 'يبدأ الإفطار خلال',
      'offline_msg': 'وضع غير متصل بالإنترنت • ذاكرة التخزين المؤقت',
      'loading': 'جاري تحديث أوقات الصلاة...',
      'bismillah': 'بسم الله الرحمن الرحيم',
      'change_lang': 'اللغة / Language / ভাষা',
      'active_lang': 'العربية',
      'settings': 'الإعدادات والتفضيلات',
      'home': 'الرئيسية',
      'theme_mode': 'مظهر التطبيق',
      'theme_system': 'تلقائي النظام',
      'theme_light': 'المظهر الفاتح',
      'theme_dark': 'المظهر الداكن',
      'color_scheme': 'سمة الألوان والمظهر',
      'color_emerald': 'الأخضر الزمردي',
      'color_sapphire': 'الأزرق الياقوتي',
      'color_ruby': 'الأحمر الياقوتي',
      'profile': 'ملف المستخدم والإحصائيات',
      'stats_weekly_prayers': 'الصلوات المؤداة هذا الأسبوع',
      'stats_weekly_fasts': 'أيام الصيام (آخر ٧ أيام)',
      'qaza_backlog': 'الصلوات الفائتة النشطة',
      'back_to_home': 'العودة للرئيسية',
      'active_preset': 'سمة الألوان النشطة',
      'completed': 'مكتملة',
      'days': 'أيام',
      'of_total': 'من أصل',
      'exit_warning': 'اضغط مرة أخرى للخروج',
      'current_prayer': 'الصلاة الحالية',
      'next_prayer': 'الصلاة القادمة',
      'left': 'متبقي',
      'time_elapsed': 'منقضي',
      'remaining': 'متبقي',
      'quiz': 'الاختبار القرآني',
      'tafsir_review': 'مراجعة التفسير',
      'quiz_question_count': 'سؤال',
      'quiz_points': 'نقاط',
      'quiz_next': 'السؤال التالي',
      'quiz_previous': 'السابق',
      'quiz_finish': 'إنهاء الاختبار',
      'quiz_lifetime_score': 'النتيجة الإجمالية',
      'quiz_completed_title': 'اكتمل الاختبار اليومي!',
      'quiz_completed_sub': 'لقد أجبت على جميع الأسئلة السبعة لهذا اليوم. عد غدًا لمجموعة جديدة من الأفكار القرآنية!',
      'quiz_syncing': 'مزامنة التقدم مع الخادم...',
      'quiz_synced': 'تمت مزامنة التقدم بأمان مع السحابة',
      'quiz_correct': 'صحيح',
      'quiz_incorrect': 'غير صحيح',
      'quiz_tafsir_insight': 'بصيرة التفسير',
      'quiz_pts': 'نقاط',
      'no_questions_available': 'لا توجد أسئلة متاحة',
      'no_questions_available_sub': 'لا توجد أسئلة مخصصة لهذا اليوم. يرجى المحاولة لاحقاً.',
      'quiz_no_results': 'لا توجد نتائج متاحة. يرجى إكمال اختبار اليوم أولاً.',
      'quiz_sync_error_timeout': 'انتهت مهلة الاتصال. تم حفظ التقدم محلياً.',
      'quiz_sync_error_failed': 'فشلت المزامنة. تم حفظ التقدم محلياً.',
      'explore_tools': 'المركز الروحي',
      'hub_mosques_sub': 'ابحث عن المساجد القريبة',
      'hub_quiz_sub': 'اختبر معلوماتك القرآنية',
      'hub_tracker_sub': 'سجل صلواتك اليومية',
      'hub_qaza_sub': 'تابع صلوات القضاء',
      'hub_profile_sub': 'عرض الإحصائيات والسجل',
      'hub_settings_sub': 'المظاهر وطرق الحساب',
      'qibla_finder': 'محدد القبلة',
      'hub_qibla_sub': 'ابحث عن اتجاه مكة المكرمة',
      'qibla_direction': 'اتجاه القبلة',
      'qibla_searching': 'جارٍ تحديد الموقع…',
      'qibla_error': 'تعذّر تحديد اتجاه القبلة. يرجى تفعيل الوصول للموقع.',
      'qibla_sensor_unavailable': 'حساس البوصلة غير متاح على هذا الجهاز.',
      'special_timings': 'الفترات المنهي عنها',
      'view_calendar': 'تقويم مواقيت الصلاة',
      'calendar_subtitle': 'عرض مواقيت الأسبوع والشهر والتاريخ المخصص',
      'tab_week': 'أسبوعي',
      'tab_month': 'شهري',
      'tab_date': 'اختر التاريخ',
      'tap_view_details': 'اضغط لعرض التفاصيل',
      'no_timings_found': 'لم يتم العثور على مواقيت',
      'forbidden_status': 'حالة إذن الصلاة',
      'prayer_allowed': 'الصلوات مسموح بها',
      'prayer_forbidden': 'الصلوات التطوعية منهي عنها',
      'tahajjud_prayer': 'صلاة التهجد',
      'tahajjud_desc': 'صلاة قيام الليل',
      'tahajjud_best': 'التهجد (أفضل وقت)',
      'ishraq_prayer': 'صلاة الإشراق',
      'chasht_duha': 'صلاة الضحى (Chasht)',
      'chasht_desc': 'صلاة الضحى (نفل)',
      'chasht_info_title': 'عن صلاة الضحى (الچاشت)',
      'chasht_info_body': 'الضحى هي صلاة تطوعية تؤدى بعد شروق الشمس بارتفاعها (من 45 دقيقة بعد الشروق وحتى 10 دقائق قبل الظهر). وهي سنة مؤكدة تجلب الرزق وتعد صدقة عن مفاصل البدن.',
      'ishraq_desc': 'صلاة أول النهار',
      'forbidden_sunrise': 'وقت الكراهة (عند الشروق)',
      'forbidden_zawal': 'وقت الكراهة (عند الزوال)',
      'forbidden_sunset': 'وقت الكراهة (عند الغروب)',
      'forbidden_time': 'وقت الكراهة (ممنوع)',
      'prayer_not_permitted': 'الصلاة غير مسموح بها الآن',
      'tahajjud_active': 'وقت التهجد نشط الآن',
      'state_active': 'الحالية',
      'state_upcoming': 'القادمة',
      'ishraq_active': 'وقت الإشراق نشط الآن',
      'chasht_duha_active': 'وقت الضحى نشط الآن',
      'select_language': 'اختر اللغة',
      'confirm': 'تأكيد',
      'lang_detect_desc': 'لقد حددنا لغتك بناءً على موقعك. لا تتردد في تغييرها.',
      'tahajjud_info_title': 'عن صلاة التهجد',
      'tahajjud_info_body': 'التهجد هي صلاة تطوعية تؤدى في الليل بعد الاستيقاظ من النوم. ووقتها من بعد صلاة العشاء إلى صلاة الفجر، وأفضل وقت لها هو الثلث الأخير من الليل. وهي سنة مؤكدة تجلب القرب من الله والمغفرة والطمأنينة.',
      'ishraq_info_title': 'عن صلاة الإشراق (الضحى)',
      'ishraq_info_body': 'الإشراق (وهي أول صلاة الضحى) هي صلاة تطوعية تبدأ بعد شروق الشمس بـ 15 دقيقة وتنتهي قبل الظهر بـ 10 دقائق. وصلاة الضحى تجلب البركة وتعد بمثابة صدقة عن مفاصل الجسد.',
      'close': 'إغلاق',
      'am': 'ص',
      'pm': 'م',
      'ishraq': 'الإشراق',
    },
    'bn': {
      'app_title': 'আদীন • Adeen',
      'sehri': 'সেহরি শেষ',
      'iftar': 'ইফতারের সময়',
      'fajr': 'ফজর',
      'sunrise': 'সূর্যোদয়',
      'dhuhr': 'যোহর',
      'jumah_prayer': 'জুমাহ',
      'asr': 'আসর',
      'maghrib': 'মাগরিব',
      'isha': 'এশা',
      'imsak': 'ইমসাক',
      'prayer_tracker': 'দৈনিক সালাত ট্র্যাকার',
      'qaza_tracker': 'কাযা সালাত ট্র্যাকার',
      'fasting_tracker': 'রোজা ট্র্যাকার',
      'fasted_today': 'আজ রোজা আছেন?',
      'fasting_completed': 'আলহামদুলিল্লাহ, রোজা সম্পন্ন!',
      'fasting_not_completed': 'রোজা শুরু/লগ করা হয়নি',
      'prayers_logged': 'লগ করা সালাত',
      'mosques': 'নিকটবর্তী মসজিদ',
      'mosque_data_disclaimer': 'বিশেষ দ্রষ্টব্য: মসজিদের তথ্য ও অবস্থান গুগল ম্যাপ থেকে নেওয়া হয়েছে, তাই এটি সম্পূর্ণ নির্ভুল নাও হতে পারে।',
      'search_mosques': 'সুবিধা অনুযায়ী মসজিদ ফিল্টার',
      'facility_women': 'মহিলাদের নামাজের জায়গা',
      'facility_parking': 'পার্কিং এর ব্যবস্থা',
      'facility_jummah': 'একাধিক জুম্মা জামাত',
      'iqamah_time': 'ইকামত',
      'suggest_iqamah': 'ইকামত পরিবর্তনের অনুরোধ',
      'get_directions': 'দিকনির্দেশনা পান',
      'update_iqamah_title': 'ইকামত সময় আপডেট',
      'update_success': 'ইকামত সময় সফলভাবে আপডেট হয়েছে!',
      'enter_time': 'সময় নির্বাচন করুন',
      'cancel': 'বাতিল',
      'change': 'পরিবর্তন',
      'today_prayers': 'আজকের নামাজ',
      'hijri_month_1': 'মুহাররম',
      'hijri_month_2': 'সফর',
      'hijri_month_3': 'রবিউল আউয়াল',
      'hijri_month_4': 'রবিউস সানি',
      'hijri_month_5': 'জমাদিউল আউয়াল',
      'hijri_month_6': 'জমাদিউস সানি',
      'hijri_month_7': 'রজব',
      'hijri_month_8': 'শাবান',
      'hijri_month_9': 'রমজান',
      'hijri_month_10': 'শাওয়াল',
      'hijri_month_11': 'জিলকদ',
      'hijri_month_12': 'জিলহজ্জ',
      'save': 'সংরক্ষণ',
      'distance': 'দূরত্ব',
      'km': 'কিমি',
      'method': 'গণনা পদ্ধতি',
      'calculation_settings': 'গণনা সেটিংস',
      'method_karachi': 'ইসলামী বিজ্ঞান বিশ্ববিদ্যালয়, করাচি',
      'method_isna': 'ইসলামিক সোসাইটি অফ উত্তর আমেরিকা (ISNA)',
      'method_mwl': 'মুসলিম ওয়ার্ল্ড লিগ (MWL)',
      'method_umm_al_qura': 'উম্ম আল-কুরা বিশ্ববিদ্যালয়, মক্কা',
      'method_egyptian': 'মিশরীয় জেনারেল অথরিটি অফ সার্ভে',
      'method_gulf': 'উপসাগরীয় অঞ্চল',
      'method_kuwait': 'কুয়েত',
      'method_qatar': 'কাতার',
      'method_singapore': 'এমইউআইএস (সিঙ্গাপুর)',
      'method_turkey': 'দিয়ানাত (তুরস্ক)',
      'method_jafari': 'লেভা ইনস্টিটিউট, কোম (জাফরি)',
      'method_tehran': 'জিওফিজিক্স ইনস্টিটিউট, তেহরান বিশ্ববিদ্যালয়',
      'method_france': 'ইসলামিক ইউনিয়ন অর্গানাইজেশন ফ্রান্স',
      'method_russia': 'রাশিয়ার মুসলিম আধ্যাত্মিক প্রশাসন',
      'method_moonsighting': 'মুনসাইটিং কমিটি ওয়ার্ল্ডওয়াইড',
      'method_dubai': 'দুবাই (পরীক্ষামূলক)',
      'method_jakim': 'JAKIM, মালয়েশিয়া',
      'method_tunisia': 'তিউনিসিয়া',
      'method_algeria': 'আলজেরিয়া',
      'method_kemenag': 'কেমেনাগ (ইন্দোনেশিয়া)',
      'method_morocco': 'মরক্কো',
      'method_portugal': 'কমিউনিডেড ইসলামিকা দে লিসবোয়া, পর্তুগাল',
      'method_jordan': 'ধর্ম মন্ত্রণালয়, জর্ডান',
      'juristic_method': 'মাযহাব (আসর গণনা)',
      'school_standard': 'সাধারণ (শাফেয়ী, মালেকী, হাম্বলী)',
      'school_hanafi': 'হানাফী',
      'next_prayer_in': 'পরবর্তী সালাত শুরু',
      'sehri_ends_in': 'সেহরি শেষ হতে',
      'iftar_in': 'ইফতার শুরু হতে',
      'offline_msg': 'অফলাইন মোড • লোকাল ক্যাশ',
      'loading': 'সালাতের সময় আপডেট হচ্ছে...',
      'bismillah': 'পরম করুণাময় ও অসীম দয়ালু আল্লাহর নামে',
      'change_lang': 'ভাষা পরিবর্তন / Language',
      'active_lang': 'বাংলা',
      'settings': 'সেটিংস এবং পছন্দসমূহ',
      'home': 'হোম',
      'theme_mode': 'থিম মোড',
      'theme_system': 'সিস্টেম ডিফল্ট',
      'theme_light': 'লাইট মোড',
      'theme_dark': 'ডার্ক মোড',
      'color_scheme': 'কালার স্কিম',
      'color_emerald': 'পান্না সবুজ (Emerald)',
      'color_sapphire': 'নীলকান্তমণি (Sapphire)',
      'color_ruby': 'চুনি লাল (Ruby)',
      'profile': 'ব্যবহারকারীর প্রোফাইল এবং পরিসংখ্যান',
      'stats_weekly_prayers': 'সাপ্তাহিক সালাত সম্পন্ন',
      'stats_weekly_fasts': 'সাপ্তাহিক রোজা সম্পন্ন (গত ৭ দিন)',
      'qaza_backlog': 'সক্রিয় কাযা সালাত',
      'back_to_home': 'হোমে ফিরে যান',
      'active_preset': 'সক্রিয় কালার থিম',
      'completed': 'সম্পন্ন',
      'days': 'দিন',
      'of_total': 'এর মধ্যে',
      'exit_warning': 'অ্যাপ থেকে বের হতে আবার ব্যাক প্রেস করুন',
      'current_prayer': 'বর্তমান সালাত',
      'next_prayer': 'পরবর্তী সালাত',
      'left': 'বাকি',
      'time_elapsed': 'অতিবাহিত',
      'remaining': 'অবশিষ্ট',
      'quiz': 'কোরআনিক কুইজ',
      'tafsir_review': 'তাফসীর পর্যালোচনা',
      'quiz_question_count': 'প্রশ্ন',
      'quiz_points': 'পয়েন্ট',
      'quiz_next': 'পরবর্তী প্রশ্ন',
      'quiz_previous': 'পূর্ববর্তী',
      'quiz_finish': 'কুইজ শেষ করুন',
      'quiz_lifetime_score': 'আজীবন স্কোর',
      'quiz_completed_title': 'আজকের কুইজ সম্পন্ন!',
      'quiz_completed_sub': 'আপনি আজকের ৭টি প্রশ্নের সবগুলোর উত্তর দিয়েছেন। নতুন কোরআনিক অন্তর্দৃষ্টির জন্য আগামীকাল আবার আসুন!',
      'quiz_syncing': 'সার্ভারের সাথে প্রগতি সিঙ্ক করা হচ্ছে...',
      'quiz_synced': 'প্রগতি ক্লাউডের সাথে নিরাপদে সিঙ্ক হয়েছে',
      'quiz_correct': 'সঠিক',
      'quiz_incorrect': 'ভুল',
      'quiz_tafsir_insight': 'তাফসীর অন্তর্দৃষ্টি',
      'quiz_pts': 'পয়েন্ট',
      'no_questions_available': 'কোন প্রশ্ন উপলব্ধ নেই',
      'no_questions_available_sub': 'আজকের জন্য কোন প্রশ্ন কনফিগার করা নেই। অনুগ্রহ করে পরে আবার চেষ্টা করুন।',
      'quiz_no_results': 'কোন ফলাফল উপলব্ধ নেই। অনুগ্রহ করে প্রথমে আজকের কুইজটি সম্পূর্ণ করুন।',
      'quiz_sync_error_timeout': 'সংযোগের সময় শেষ হয়েছে। প্রগতি লোকালি সংরক্ষণ করা হয়েছে।',
      'quiz_sync_error_failed': 'সিঙ্ক ব্যর্থ হয়েছে। প্রগতি লোকালি সংরক্ষণ করা হয়েছে।',
      'explore_tools': 'আধ্যাত্মিক হাব',
      'hub_mosques_sub': 'নিকটবর্তী মসজিদ খুঁজুন',
      'hub_quiz_sub': 'কোরআনিক জ্ঞান পরীক্ষা করুন',
      'hub_tracker_sub': 'দৈনিক সালাত লগ করুন',
      'hub_qaza_sub': 'কাযা সালাত ট্র্যাক করুন',
      'hub_profile_sub': 'পরিসংখ্যান ও লগ দেখুন',
      'hub_settings_sub': 'থিম ও গণনা পদ্ধতি',
      'qibla_finder': 'কিবলা ফাইন্ডার',
      'hub_qibla_sub': 'মক্কার দিক খুঁজুন',
      'qibla_direction': 'কিবলার দিক',
      'qibla_searching': 'অবস্থান নির্ধারণ করা হচ্ছে…',
      'qibla_error': 'কিবলার দিক নির্ধারণ করা সম্ভব হয়নি। অনুগ্রহ করে লোকেশন চালু করুন।',
      'qibla_sensor_unavailable': 'এই ডিভাইসে কম্পাস সেন্সর পাওয়া যাচ্ছে না।',
      'special_timings': 'নিষিদ্ধ সময়',
      'view_calendar': 'সালাতের সময়সূচী ক্যালেন্ডার',
      'calendar_subtitle': 'সাপ্তাহিক, মাসিক এবং কাস্টম তারিখের সময়সূচী দেখুন',
      'tab_week': 'সাপ্তাহিক',
      'tab_month': 'মাসিক',
      'tab_date': 'তারিখ নির্বাচন',
      'tap_view_details': 'বিস্তারিত দেখতে ট্যাপ করুন',
      'no_timings_found': 'কোনো সময়সূচী পাওয়া যায়নি',
      'forbidden_status': 'নামাজ পড়ার অনুমতি',
      'prayer_allowed': 'সালাত আদায় করা যাবে',
      'prayer_forbidden': 'নফল সালাত আদায় করা নিষিদ্ধ',
      'tahajjud_prayer': 'তাহাজ্জুদ সালাত',
      'tahajjud_desc': 'রাতের শেষভাগের সালাত',
      'tahajjud_best': 'তাহাজ্জুদ (উত্তম সময়)',
      'ishraq_prayer': 'ইশরাক সালাত',
      'chasht_duha': 'চাশত (দুহা)',
      'chasht_desc': 'পূর্বাহ্নের নফল সালাত',
      'chasht_info_title': 'চাশত (দুহা) নামাজ সম্পর্কে',
      'chasht_info_body': 'চাশত (বা দুহা) হলো সূর্য উপরে ওঠার পর আদায় করার একটি নফল নামাজ। সূর্যোদয়ের ৪৫ মিনিট পর থেকে জোহরের ১০ মিনিট পূর্ব পর্যন্ত এর সময় থাকে। এটি অত্যন্ত ফজিলতপূর্ণ সুন্নাত যা রিজিক বৃদ্ধি করে ও শরীরের প্রতিটি জোড়ের সদকা হিসেবে গণ্য হয়।',
      'ishraq_desc': 'সূর্যোদয়ের পরের সালাত',
      'forbidden_sunrise': 'সূর্যোদয়ের নিষিদ্ধ সময়',
      'forbidden_zawal': 'জাওয়াল (দ্বিপ্রহর) নিষিদ্ধ সময়',
      'forbidden_sunset': 'সূর্যাস্তের নিষিদ্ধ সময়',
      'forbidden_time': 'নিষিদ্ধ সময়',
      'prayer_not_permitted': 'এখন সালাত আদায় করা নিষিদ্ধ',
      'tahajjud_active': 'তাহাজ্জুদের সময় চলছে',
      'state_active': 'বর্তমান',
      'state_upcoming': 'আসন্ন',
      'ishraq_active': 'ইশরাকের সময় চলছে',
      'chasht_duha_active': 'চাশত (দুহা) এর সময় চলছে',
      'select_language': 'ভাষা নির্বাচন করুন',
      'confirm': 'নিশ্চিত করুন',
      'lang_detect_desc': 'আপনার অবস্থানের উপর ভিত্তি করে আমরা ভাষা সনাক্ত করেছি। চাইলে পরিবর্তন করতে পারেন।',
      'tahajjud_info_title': 'তাহাজ্জুদ নামাজ সম্পর্কে',
      'tahajjud_info_body': 'তাহাজ্জুদ হলো ঘুমানোর পর রাতে জেগে আদায় করার একটি নফল নামাজ। এশার পর থেকে ফজর পর্যন্ত এর সময় থাকে, তবে রাতের শেষ তৃতীয়াংশ সবচেয়ে উত্তম সময়। এটি একটি অত্যন্ত ফজিলতপূর্ণ সুন্নাত যা আধ্যাত্মিক উন্নতি ও প্রশান্তি বয়ে আনে।',
      'ishraq_info_title': 'ইশরাক (দুহা) নামাজ সম্পর্কে',
      'ishraq_info_body': 'ইশরাক (যা চাশত বা দুহার শুরুর সময়) হলো একটি নফল সকালের নামাজ। সূর্যোদয়ের ১৫ মিনিট পর এর সময় শুরু হয় এবং যোহরের ১০ মিনিট আগে শেষ হয়। ফজরের পর জায়নামাজে বসে জিকির করে এই নামাজ আদায় করা অত্যন্ত সওয়াবের কাজ।',
      'close': 'বন্ধ করুন',
      'am': 'এ.এম.',
      'pm': 'পি.এম.',
      'ishraq': 'ইশরাক',
    },
    'hi': {
      'app_title': 'अदीन • Adeen',
      'sehri': 'सेहरी समाप्ति',
      'iftar': 'इफ्तार का समय',
      'fajr': 'फज्र',
      'sunrise': 'सूर्योदय',
      'dhuhr': 'धुहर',
      'jumah_prayer': 'जुमा',
      'asr': 'असर',
      'maghrib': 'मग़रिब',
      'isha': 'ईशा',
      'imsak': 'इमसाक',
      'prayer_tracker': 'दैनिक प्रार्थना ट्रैकर',
      'qaza_tracker': 'कज़ा ट्रैकर',
      'fasting_tracker': 'रमज़ान उपवास ट्रैकर',
      'fasted_today': 'क्या आज उपवास है?',
      'fasting_completed': 'अल्हम्दुलिल्लाह, उपवास पूर्ण!',
      'fasting_not_completed': 'उपवास शुरू नहीं हुआ',
      'prayers_logged': 'लॉग की गई प्रार्थनाएँ',
      'mosques': 'आस-पास की मस्जिदें',
      'mosque_data_disclaimer': 'नोट: मस्जिद के विवरण और स्थान Google मानचित्र से प्राप्त किए गए हैं और पूरी तरह से सटीक नहीं हो सकते हैं।',
      'search_mosques': 'सुविधा द्वारा फ़िल्टर करें',
      'facility_women': 'महिला वर्ग',
      'facility_parking': 'पार्किंग क्षेत्र',
      'facility_jummah': 'एकाधिक जुम्मा पाली',
      'iqamah_time': 'इक़ामह',
      'suggest_iqamah': 'इक़ामह बदलाव का सुझाव दें',
      'get_directions': 'दिशा-निर्देश प्राप्त करें',
      'update_iqamah_title': 'इक़ामह समय का सुझाव दें',
      'update_success': 'इक़ामह समय सफलतापूर्वक अपडेट किया गया!',
      'enter_time': 'समय चुनें',
      'cancel': 'रद्द करें',
      'change': 'बदलें',
      'today_prayers': 'आज की प्रार्थनाएँ',
      'hijri_month_1': 'मुहर्रम',
      'hijri_month_2': 'सफ़र',
      'hijri_month_3': 'रबी अल-अव्वल',
      'hijri_month_4': 'रबी अल-थानी',
      'hijri_month_5': 'जुमादा अल-अव्वल',
      'hijri_month_6': 'जुमादा अल-थानी',
      'hijri_month_7': 'रजब',
      'hijri_month_8': 'शाबान',
      'hijri_month_9': 'रमजान',
      'hijri_month_10': 'शव्वाल',
      'hijri_month_11': 'धु अल-क़ीदाह',
      'hijri_month_12': 'धु अल-हिजाह',
      'save': 'सहेजें',
      'distance': 'दूरी',
      'km': 'किमी',
      'method': 'गणना विधि',
      'calculation_settings': 'गणना सेटिंग्स',
      'method_karachi': 'इस्लामिक विज्ञान विश्वविद्यालय, कराची',
      'method_isna': 'इस्लामिक सोसाइटी ऑफ नॉर्थ अमेरिका (ISNA)',
      'method_mwl': 'मुस्लिम वर्ल्ड लीग (MWL)',
      'method_umm_al_qura': 'उम अल-कुरा विश्वविद्यालय, मक्का',
      'method_egyptian': 'मिस्र के जनरल सर्वे प्राधिकरण',
      'method_gulf': 'खाड़ी क्षेत्र',
      'method_kuwait': 'कुवैत',
      'method_qatar': 'कतर',
      'method_singapore': 'म्यूइस (सिंगापुर)',
      'method_turkey': 'दियानet (तुर्की)',
      'method_jafari': 'लेवा इंस्टीट्यूट, क़ोम (जाफरी)',
      'method_tehran': 'भू-भौतिकी संस्थान, तेहरान विश्वविद्यालय',
      'method_france': 'इस्लामिक यूनियन ऑर्गनाइज़ेशन, फ्रांस',
      'method_russia': 'रूस के मुसलमानों का आध्यात्मिक प्रशासन',
      'method_moonsighting': 'मूनसाइटिंग कमेटी वर्ल्डवाइड',
      'method_dubai': 'दुबई (प्रायोगिक)',
      'method_jakim': 'JAKIM, मलेशिया',
      'method_tunisia': 'ट्यूनीशिया',
      'method_algeria': 'अल्जीरिया',
      'method_kemenag': 'केमेनाग (इंडोनेशिया)',
      'method_morocco': 'मोरक्को',
      'method_portugal': 'कमुनिदाद इस्लामिका दे लिस्बोआ, पुर्तगाल',
      'method_jordan': 'मंत्रालय यावकाफ, जॉर्डन',
      'juristic_method': 'न्यायशास्त्र पद्धति (अस्र)',
      'school_standard': 'मानक (शाफ़ई, मालिकी, हनबली)',
      'school_hanafi': 'हनफ़ी',
      'next_prayer_in': 'अगली प्रार्थना में',
      'sehri_ends_in': 'सेहरी समाप्त होने में',
      'iftar_in': 'इफ्तार शुरू होने में',
      'offline_msg': 'ऑफ़लाइन मोड • स्थानीय कैश',
      'loading': 'प्रार्थना का समय अपडेट हो रहा है...',
      'bismillah': 'अल्लाह के नाम से, जो अत्यंत कृपालु और दयावान है',
      'change_lang': 'भाषा बदलें / Language',
      'active_lang': 'हिन्दी',
      'settings': 'सेटिंग्स और प्राथमिकताएं',
      'home': 'होम',
      'theme_mode': 'थीम मोड',
      'theme_system': 'सिस्टम डिफ़ॉल्ट',
      'theme_light': 'लाइट मोड',
      'theme_dark': 'डार्क मोड',
      'color_scheme': 'रंग योजना प्रीसेट',
      'color_emerald': 'पन्ना हरा (Emerald)',
      'color_sapphire': 'नीलम नीला (Sapphire)',
      'color_ruby': 'रूबी लाल (Ruby)',
      'profile': 'प्रोफ़ाइल और आँकड़े',
      'stats_weekly_prayers': 'साप्ताहिक प्रार्थनाएँ पूर्ण',
      'stats_weekly_fasts': 'लॉग किए गए उपवास (अंतिम 7 दिन)',
      'qaza_backlog': 'सक्रिय कज़ा बैकलॉग',
      'back_to_home': 'मुख्य पृष्ठ पर वापस',
      'active_preset': 'सक्रिय रंग थीम',
      'completed': 'पूर्ण',
      'days': 'दिन',
      'of_total': 'का',
      'exit_warning': 'बाहर निकलने के लिए फिर से वापस दबाएं',
      'current_prayer': 'वर्तमान प्रार्थना',
      'next_prayer': 'अगली प्रार्थना',
      'left': 'शेष',
      'time_elapsed': 'बीता हुआ',
      'remaining': 'बाकी',
      'quiz': 'क़ुरानिक क्विज़',
      'tafsir_review': 'तफ़सीर समीक्षा',
      'quiz_question_count': 'प्रश्न',
      'quiz_points': 'अंक',
      'quiz_next': 'अगला प्रश्न',
      'quiz_previous': 'पिछला',
      'quiz_finish': 'क्विज़ समाप्त करें',
      'quiz_lifetime_score': 'लाइफटाइम स्कोर',
      'quiz_completed_title': 'दैनिक क्विज़ पूरा हुआ!',
      'quiz_completed_sub': 'आपने आज के सभी 7 प्रश्नों के उत्तर दे दिए हैं। नई क़ुरानिक अंतर्दृष्टि के लिए कल फिर आएं!',
      'quiz_syncing': 'सर्वर के साथ सिंक हो रहा है...',
      'quiz_synced': 'प्रगति क्लाउड के साथ सुरक्षित रूप से सिंक हो गई है',
      'quiz_correct': 'सही',
      'quiz_incorrect': 'गलत',
      'quiz_tafsir_insight': 'तफ़सीर अंतर्दृष्टि',
      'quiz_pts': 'अंक',
      'no_questions_available': 'कोई प्रश्न उपलब्ध नहीं',
      'no_questions_available_sub': 'आज के लिए कोई प्रश्न कॉन्फ़िगर नहीं किया गया है। कृपया बाद में पुनः प्रयास करें।',
      'quiz_no_results': 'कोई परिणाम उपलब्ध नहीं है। कृपया पहले आज की प्रश्नोत्तरी पूरी करें।',
      'quiz_sync_error_timeout': 'कनेक्शन का समय समाप्त हो गया। प्रगति स्थानीय रूप से सहेजी गई।',
      'quiz_sync_error_failed': 'सिंक विफल रहा। प्रगति स्थानीय रूप से सहेजी गई।',
      'explore_tools': 'आध्यात्मिक हब',
      'hub_mosques_sub': 'आस-पास की मस्जिदें खोजें',
      'hub_quiz_sub': 'क़ुरानिक ज्ञान का परीक्षण करें',
      'hub_tracker_sub': 'दैनिक प्रार्थना लॉग करें',
      'hub_qaza_sub': 'छूटी हुई प्रार्थनाएँ ट्रैक करें',
      'hub_profile_sub': 'आंकड़े और लॉग देखें',
      'hub_settings_sub': 'थीम और गणना विधि',
      'qibla_finder': 'क़िबला फाइंडर',
      'hub_qibla_sub': 'मक्का की दिशा खोजें',
      'qibla_direction': 'क़िबला दिशा',
      'qibla_searching': 'स्थान निर्धारित किया जा रहा है…',
      'qibla_error': 'क़िबला दिशा निर्धारित करने में असमर्थ। कृपया स्थान पहुँच सक्षम करें।',
      'qibla_sensor_unavailable': 'इस डिवाइस पर कम्पास सेंसर उपलब्ध नहीं है।',
      'special_timings': 'वर्जित अवधियाँ',
      'view_calendar': 'प्रार्थना समय सारिणी कैलेंडर',
      'calendar_subtitle': 'साप्ताहिक, मासिक और कस्टम तिथि समय देखें',
      'tab_week': 'साप्ताहिक',
      'tab_month': 'मासिक',
      'tab_date': 'दिनांक चुनें',
      'tap_view_details': 'विवरण देखने के लिए टैप करें',
      'no_timings_found': 'कोई समय नहीं मिला',
      'forbidden_status': 'प्रार्थना अनुमति स्थिति',
      'prayer_allowed': 'प्रार्थनाओं की अनुमति है',
      'prayer_forbidden': 'स्वैच्छिक प्रार्थनाएँ वर्जित हैं',
      'tahajjud_prayer': 'तहज्जुद प्रार्थना',
      'tahajjud_desc': 'रात्रि जागरण प्रार्थना',
      'tahajjud_best': 'तहज्जुद (सर्वोत्तम समय)',
      'ishraq_prayer': 'इशराक प्रार्थना',
      'chasht_duha': 'चाश्त (दुहा) प्रार्थना',
      'chasht_desc': 'पूर्वाह्न की स्वैच्छिक प्रार्थना',
      'chasht_info_title': 'चाश्त (दुहा) नमाज़ के बारे में',
      'chasht_info_body': 'चाश्त (या दुहा) एक स्वैच्छिक नमाज़ है जो सूरज के ऊपर चढ़ने पर पढ़ी जाती है। इसका समय सूर्योदय के 45 मिनट बाद से शुरू होकर ज़ुहर से 10 मिनट पहले समाप्त होता है। यह एक अत्यधिक अनुशंसित सुन्नत है जो समृद्धि लाती है।',
      'ishraq_desc': 'सुबह की प्रार्थना',
      'forbidden_sunrise': 'सूर्योदय वर्जित अवधि',
      'forbidden_zawal': 'जवाल (मध्याह्न) वर्जित',
      'forbidden_sunset': 'सूर्यास्त वर्जित अवधि',
      'forbidden_time': 'वर्जित समय',
      'prayer_not_permitted': 'प्रार्थना की अनुमति नहीं है',
      'tahajjud_active': 'तहज्जुद का समय सक्रिय है',
      'state_active': 'वर्तमान',
      'state_upcoming': 'आगामी',
      'ishraq_active': 'इशराक का समय सक्रिय है',
      'chasht_duha_active': 'चाश्त (दुहा) का समय सक्रिय है',
      'select_language': 'भाषा चुनें',
      'confirm': 'पुष्टि करें',
      'lang_detect_desc': 'हमने आपके स्थान के आधार पर आपकी भाषा का पता लगाया है। आप इसे बदल सकते हैं।',
      'tahajjud_info_title': 'तहज्जुद नमाज़ के बारे में',
      'tahajjud_info_body': 'तहज्जुद एक स्वैच्छिक रात की नमाज़ है जो सोने के बाद जागने पर पढ़ी जाती है। इसका समय ईशा से फज्र तक रहता है, जिसमें सबसे अच्छा समय रात का आखिरी तीसरा हिस्सा है। यह एक अत्यधिक अनुशंसित सुन्नत है जो आध्यात्मिक शांति लाती है।',
      'ishraq_info_title': 'इशराक (दुहा) नमाज़ के बारे में',
      'ishraq_info_body': 'इशराक (जिसे दुहा की शुरुआत भी कहा जाता है) सुबह की एक स्वैच्छिक नमाज़ है। इसका समय सूर्योदय के 15 मिनट बाद शुरू होता है और ज़ुहर से 10 मिनट पहले समाप्त होता है। इसे पढ़ना अत्यंत फलदायी और बरकत वाला है।',
      'close': 'बंद करें',
      'am': 'ए.एम.',
      'pm': 'पी.एम.',
      'ishraq': 'इशराक',
    },
    'ur': {
      'app_title': 'عدین • Adeen',
      'sehri': 'سحری کا اختتام',
      'iftar': 'افطار کا وقت',
      'fajr': 'فجر',
      'sunrise': 'طلوعِ آفتاب',
      'dhuhr': 'ظہر',
      'jumah_prayer': 'جمعہ',
      'asr': 'عصر',
      'maghrib': 'مغرب',
      'isha': 'عشاء',
      'imsak': 'امساک',
      'prayer_tracker': 'نماز کا ٹریکر',
      'qaza_tracker': 'قضا نماز ٹریکر',
      'fasting_tracker': 'روزہ ٹریکر',
      'fasted_today': 'کیا آج روزہ ہے؟',
      'fasting_completed': 'الحمدللہ، روزہ مکمل!',
      'fasting_not_completed': 'روزہ شروع نہیں کیا گیا',
      'prayers_logged': 'اداکردہ نمازیں',
      'mosques': 'قریبی مساجد',
      'mosque_data_disclaimer': 'نوٹ: مساجد کی تفصیلات اور مقامات گوگل میپس سے حاصل کیے گئے ہیں اور ہو سکتا ہے مکمل طور پر درست نہ ہوں۔',
      'search_mosques': 'مساجد کی فلٹرنگ',
      'facility_women': 'خواتین کے لیے جگہ',
      'facility_parking': 'پارکنگ کی جگہ',
      'facility_jummah': 'متعدد نمازِ جمعہ',
      'iqamah_time': 'اقامت',
      'suggest_iqamah': 'اقامت کے وقت کی تجویز',
      'get_directions': 'راستہ معلوم کریں',
      'update_iqamah_title': 'اقامت کا وقت تجویز کریں',
      'update_success': 'اقامت کا وقت کامیابی سے تبدیل ہو گیا!',
      'enter_time': 'وقت منتخب کریں',
      'cancel': 'منسوخ کریں',
      'change': 'تبدیل کریں',
      'today_prayers': 'آج کی نمازیں',
      'hijri_month_1': 'محرم',
      'hijri_month_2': 'صفر',
      'hijri_month_3': 'ربیع الاول',
      'hijri_month_4': 'ربیع الثانی',
      'hijri_month_5': 'جمادی الاول',
      'hijri_month_6': 'جمادی الثانی',
      'hijri_month_7': 'رجب',
      'hijri_month_8': 'شعبان',
      'hijri_month_9': 'رمضان',
      'hijri_month_10': 'شوال',
      'hijri_month_11': 'ذوالقعدہ',
      'hijri_month_12': 'ذوالحجہ',
      'save': 'محفوظ کریں',
      'distance': 'فاصلہ',
      'km': 'کلو میٹر',
      'method': 'طریقہ کارِ حساب',
      'calculation_settings': 'حساب کے اصول',
      'method_karachi': 'جامعہ علوم اسلامیہ، کراچی',
      'method_isna': 'اسلامک سوسائٹی آف نارتھ امریکہ (ISNA)',
      'method_mwl': 'رابطہ عالم اسلامی',
      'method_umm_al_qura': 'جامعہ ام القراء، مکہ مکرمہ',
      'method_egyptian': 'مصری جنرل سروے اتھارٹی',
      'method_gulf': 'خلیج کا خطہ',
      'method_kuwait': 'کویت',
      'method_qatar': 'قطر',
      'method_singapore': 'ایم یو آئی ایس (سنگاپور)',
      'method_turkey': 'دیانت (ترکی)',
      'method_jafari': 'لیوا انسٹیٹیوٹ، قم (جعفری)',
      'method_tehran': 'جیوفزکس انسٹیٹیوٹ، یونیورسٹی آف تہران',
      'method_france': 'اسلامک یونین آرگنائزیشن، فرانس',
      'method_russia': 'روس کے مسلمانوں کا روحانی ادارہ',
      'method_moonsighting': 'مون سائٹنگ کمیٹی ورلڈوائڈ',
      'method_dubai': 'دبئی (تجرباتی)',
      'method_jakim': 'JAKIM, ملائیشیا',
      'method_tunisia': 'تیونس',
      'method_algeria': 'الجزائر',
      'method_kemenag': 'کیمناگ (انڈونیشیا)',
      'method_morocco': 'مراکش',
      'method_portugal': 'کمیونیڈاد اسلامیکا دے لیسبوا، پرتگال',
      'method_jordan': 'وزارت اوقاف، اردن',
      'juristic_method': 'فقہی مسلک (عصر)',
      'school_standard': 'شافعی، مالکی، حنبلی (جمہور)',
      'school_hanafi': 'حنفی',
      'next_prayer_in': 'اگلی نماز میں وقت',
      'sehri_ends_in': 'سحری کے اختتام میں',
      'iftar_in': 'افطار کے وقت میں',
      'offline_msg': 'آف لائن موڈ • مقامی کیش',
      'loading': 'اوقاتِ نماز اپ ڈیٹ ہو رہے ہیں...',
      'bismillah': 'اللہ کے نام سے جو بڑا مہربان نہایت رحم والا ہے',
      'change_lang': 'زبان تبدیل کریں / Language',
      'active_lang': 'اردو',
      'settings': 'ترجیحات اور ترتیبات',
      'home': 'ہوم',
      'theme_mode': 'تھیم کا طریقہ کار',
      'theme_system': 'سسٹم ڈیفالٹ',
      'theme_light': 'لائٹ موڈ',
      'theme_dark': 'ڈارک موڈ',
      'color_scheme': 'رنگوں کی تھیم',
      'color_emerald': 'سبز زمرد',
      'color_sapphire': 'نیلم نیلا',
      'color_ruby': 'یاقوت سرخ',
      'profile': 'پروفائل اور اعداد و شمار',
      'stats_weekly_prayers': 'ہفتہ وار نمازیں مکمل',
      'stats_weekly_fasts': 'درج کردہ روزے (آخری 7 دن)',
      'qaza_backlog': 'بقیہ قضا نمازیں',
      'back_to_home': 'مرکزی صفحہ پر واپسی',
      'active_preset': 'سرگرم رنگوں کی تھیم',
      'completed': 'مکمل',
      'days': 'دن',
      'of_total': 'میں سے',
      'exit_warning': 'باہر نکلنے کے لیے دوبارہ دبائیں',
      'current_prayer': 'موجودہ نماز',
      'next_prayer': 'اگلی نماز',
      'left': 'باقی',
      'time_elapsed': 'گزر چکا',
      'remaining': 'باقی',
      'quiz': 'قرآنی کوئز',
      'tafsir_review': 'تفسیر کا جائزہ',
      'quiz_question_count': 'سوال',
      'quiz_points': 'پوائنٹس',
      'quiz_next': 'اگلا سوال',
      'quiz_previous': 'پچھلا',
      'quiz_finish': 'کوئز مکمل کریں',
      'quiz_lifetime_score': 'لائف ٹائم اسکور',
      'quiz_completed_title': 'روزانہ کوئز مکمل ہو گیا!',
      'quiz_completed_sub': 'آپ نے آج کے تمام 7 سوالات کے جوابات دے دیے ہیں۔ نئی قرآنی معلومات کے لیے کل دوبارہ تشریف لائیں!',
      'quiz_syncing': 'سرور کے ساتھ ہم آہنگ ہو رہا ہے...',
      'quiz_synced': 'پیش رفت محفوظ طریقے سے کلاؤڈ کے ساتھ ہم آہنگ ہو گئی ہے',
      'quiz_correct': 'درست',
      'quiz_incorrect': 'غلط',
      'quiz_tafsir_insight': 'تفسیر کی بصیرت',
      'quiz_pts': 'پوائنٹس',
      'no_questions_available': 'کوئی سوالات دستیاب نہیں ہیں',
      'no_questions_available_sub': 'آج کے لیے کوئی سوالات ترتیب نہیں دیے گئے ہیں۔ براہ کرم بعد میں دوبارہ کوشش کریں۔',
      'quiz_no_results': 'کوئی نتائج دستیاب نہیں ہیں۔ براہ کرم پہلے آج کا کوئز مکمل کریں۔',
      'quiz_sync_error_timeout': 'کنکشن کا وقت ختم ہو گیا۔ پیش رفت مقامی طور پر محفوظ کر لی گئی۔',
      'quiz_sync_error_failed': 'ہم آہنگی ناکام ہو گئی۔ پیش رفت مقامی طور پر محفوظ کر لی گئی۔',
      'explore_tools': 'روحانی مرکز',
      'hub_mosques_sub': 'قریبی مساجد تلاش کریں',
      'hub_quiz_sub': 'قرآنی معلومات کا امتحان لیں',
      'hub_tracker_sub': 'روزانہ کی نمازیں درج کریں',
      'hub_qaza_sub': 'قضا نمازوں کا حساب رکھیں',
      'hub_profile_sub': 'اعداد و شمار اور لاگ دیکھیں',
      'hub_settings_sub': 'تھیم اور حساب کتاب',
      'qibla_finder': 'قبلہ فائنڈر',
      'hub_qibla_sub': 'مکہ کی سمت معلوم کریں',
      'qibla_direction': 'قبلہ کی سمت',
      'qibla_searching': 'مقام معلوم کیا جا رہا ہے…',
      'qibla_error': 'قبلہ کی سمت معلوم نہیں ہو سکی۔ براہ کرم مقام تک رسائی فعال کریں۔',
      'qibla_sensor_unavailable': 'اس ڈیوائس پر کمپاس سینسر دستیاب نہیں ہے۔',
      'special_timings': 'ممنوعہ اوقات',
      'view_calendar': 'نماز کا اوقات نامہ کیلنڈر',
      'calendar_subtitle': 'ہفتہ وار، ماہانہ اور حسب ضرورت تاریخ کے اوقات دیکھیں',
      'tab_week': 'ہفتہ وار',
      'tab_month': 'ماہانہ',
      'tab_date': 'تاریخ منتخب کریں',
      'tap_view_details': 'تفصیلات دیکھنے کے لیے ٹیپ کریں',
      'no_timings_found': 'اوقات دستیاب نہیں ہیں',
      'forbidden_status': 'نماز کی اجازت کی صورتحال',
      'prayer_allowed': 'نمازوں کی اجازت ہے',
      'prayer_forbidden': 'نفل نمازیں پڑھنا ممنوع ہے',
      'tahajjud_prayer': 'نمازِ تہجد',
      'tahajjud_desc': 'رات کی نماز',
      'tahajjud_best': 'تہجد (افضل وقت)',
      'ishraq_prayer': 'نمازِ اشراق',
      'chasht_duha': 'نمازِ چاشت (ضحیٰ)',
      'chasht_desc': 'چاشت کی نفل نماز',
      'chasht_info_title': 'نمازِ چاشت کے بارے میں',
      'chasht_info_body': 'چاشت (یا ضحیٰ) ایک نفل نماز ہے جو سورج بلند ہونے پر پڑھی جاتی ہے۔ اس کا وقت طلوع آفتاب کے 45 منٹ بعد سے شروع ہو کر زوال سے 10 منٹ پہلے تک ہے۔ یہ رزق میں برکت اور جسم کے ہر جوڑ کے صدقہ کا ذریعہ ہے۔',
      'ishraq_desc': 'صبح کی نماز',
      'forbidden_sunrise': 'طلوعِ آفتاب کا ممنوعہ وقت',
      'forbidden_zawal': 'زوال (دوپہر) کا ممنوعہ وقت',
      'forbidden_sunset': 'غروبِ آفتاب کا ممنوعہ وقت',
      'forbidden_time': 'ممنوعہ وقت',
      'prayer_not_permitted': 'اب نماز پڑھنا ممنوع ہے',
      'tahajjud_active': 'تہجد کا وقت شروع ہے',
      'state_active': 'موجودہ',
      'state_upcoming': 'آئندہ',
      'ishraq_active': 'اشراق کا وقت شروع ہے',
      'chasht_duha_active': 'چاشت (ضحیٰ) کا وقت شروع ہے',
      'select_language': 'زبان منتخب کریں',
      'confirm': 'تصدیق کریں',
      'lang_detect_desc': 'ہم نے آپ کے مقام کی بنیاد پر آپ کی زبان کا پتہ لگایا ہے۔ بلا جھجھک اسے تبدیل کریں۔',
      'tahajjud_info_title': 'تہجد کی نماز کے بارے میں',
      'tahajjud_info_body': 'تہجد ایک نفل نماز ہے جو رات کو سونے کے بعد اٹھ کر پڑھی جاتی ہے۔ اس کا وقت عشاء سے فجر تک ہے، اور بہترین وقت رات کا آخری تہائی حصہ ہے۔ یہ ایک نہایت فضیلت والی سنت ہے جو روحانی قربت کا ذریعہ ہے۔',
      'ishraq_info_title': 'اشراق (ضحیٰ) کی نماز کے بارے میں',
      'ishraq_info_body': 'اشراق (جو کہ ضحیٰ یا چاشت کا ابتدائی وقت ہے) صبح کی نفل نماز ہے۔ اس کا وقت طلوعِ آفتاب کے 15 منٹ بعد شروع ہوتا ہے اور ظہر سے 10 منٹ پہلے ختم ہوتا ہے۔ اسے پڑھنا بے شمار برکات اور ثواب کا باعث ہے۔',
      'close': 'بند کریں',
      'am': 'ص',
      'pm': 'م',
      'ishraq': 'اشراق',
    },
    'id': {
      'app_title': 'Adeen • عدين',
      'sehri': 'Sahur Berakhir',
      'iftar': 'Waktu Buka Puasa',
      'fajr': 'Subuh',
      'sunrise': 'Terbit Fajar',
      'dhuhr': 'Dzuhur',
      'jumah_prayer': 'Jum\'at',
      'asr': 'Ashar',
      'maghrib': 'Maghrib',
      'isha': 'Isya',
      'imsak': 'Imsak',
      'prayer_tracker': 'Pelacak Shalat Harian',
      'qaza_tracker': 'Pelacak Qadha',
      'fasting_tracker': 'Pelacak Puasa Ramadan',
      'fasted_today': 'Puasa Hari Ini?',
      'fasting_completed': 'Alhamdulillah, Puasa Selesai!',
      'fasting_not_completed': 'Puasa belum dimulai/dicatat',
      'prayers_logged': 'Shalat Dicatat',
      'mosques': 'Masjid Terdekat',
      'mosque_data_disclaimer': 'Catatan: Detail dan lokasi masjid diambil dari Google Maps dan mungkin tidak sepenuhnya akurat.',
      'search_mosques': 'Filter Masjid',
      'facility_women': 'Ruang Wanita',
      'facility_parking': 'Tempat Parkir',
      'facility_jummah': 'Beberapa Gelombang Jumatan',
      'iqamah_time': 'Iqamah',
      'suggest_iqamah': 'Usulkan Waktu Iqamah',
      'get_directions': 'Petunjuk Arah',
      'update_iqamah_title': 'Usulkan Waktu Iqamah baru',
      'update_success': 'Waktu Iqamah berhasil diperbarui!',
      'enter_time': 'Pilih Waktu',
      'cancel': 'Batal',
      'change': 'Ubah',
      'today_prayers': 'Salat Hari Ini',
      'hijri_month_1': 'Muharram',
      'hijri_month_2': 'Safar',
      'hijri_month_3': 'Rabiul Awal',
      'hijri_month_4': 'Rabiul Akhir',
      'hijri_month_5': 'Jumadil Awal',
      'hijri_month_6': 'Jumadil Akhir',
      'hijri_month_7': 'Rajab',
      'hijri_month_8': 'Sya\'ban',
      'hijri_month_9': 'Ramadhan',
      'hijri_month_10': 'Syawal',
      'hijri_month_11': 'Dzulqadah',
      'hijri_month_12': 'Dzulhijjah',
      'save': 'Simpan',
      'distance': 'Jarak',
      'km': 'km',
      'method': 'Metode Perhitungan',
      'calculation_settings': 'Pengaturan Perhitungan',
      'method_karachi': 'Universitas Ilmu Islam, Karachi',
      'method_isna': 'Masyarakat Islam Amerika Utara (ISNA)',
      'method_mwl': 'Liga Dunia Muslim (MWL)',
      'method_umm_al_qura': 'Universitas Umm Al-Qura, Makkah',
      'method_egyptian': 'Otoritas Survei Umum Mesir',
      'method_gulf': 'Wilayah Teluk',
      'method_kuwait': 'Kuwait',
      'method_qatar': 'Qatar',
      'method_singapore': 'MUIS (Singapura)',
      'method_turkey': 'Diyanet (Turki)',
      'method_jafari': 'Lembaga Leva, Qom (Jafari)',
      'method_tehran': 'Institut Geofisika, Univ. Teheran',
      'method_france': 'Organisasi Islam Prancis (UOIF)',
      'method_russia': 'Administrasi Spiritual Muslim Rusia',
      'method_moonsighting': 'Komite Rukyatul Hilal Dunia',
      'method_dubai': 'Dubai (Eksperimental)',
      'method_jakim': 'JAKIM, Malaysia',
      'method_tunisia': 'Tunisia',
      'method_algeria': 'Aljazair',
      'method_kemenag': 'Kemenag (Indonesia)',
      'method_morocco': 'Maroko',
      'method_portugal': 'Komunitas Islam Lisboa, Portugal',
      'method_jordan': 'Kementerian Awqaf, Yordania',
      'juristic_method': 'Madzhab (Perhitungan Asar)',
      'school_standard': 'Standar (Syafii, Maliki, Hambali)',
      'school_hanafi': 'Hanafi',
      'next_prayer_in': 'Shalat Berikutnya dalam',
      'sehri_ends_in': 'Sahur berakhir dalam',
      'iftar_in': 'Buka puasa dalam',
      'offline_msg': 'Mode Offline • Cache Lokal',
      'loading': 'Memperbarui jadwal shalat...',
      'bismillah': 'Dengan menyebut nama Allah Yang Maha Pengasih lagi Maha Penyayang',
      'change_lang': 'Ubah Bahasa / Language',
      'active_lang': 'Bahasa Indonesia',
      'settings': 'Pengaturan & Preferensi',
      'home': 'Beranda',
      'theme_mode': 'Mode Tema',
      'theme_system': 'Default Sistem',
      'theme_light': 'Mode Terang',
      'theme_dark': 'Mode Gelap',
      'color_scheme': 'Skema Warna Tema',
      'color_emerald': 'Hijau Zamrud',
      'color_sapphire': 'Biru Safir',
      'color_ruby': 'Merah Delima',
      'profile': 'Profil & Statistik',
      'stats_weekly_prayers': 'Shalat Mingguan Selesai',
      'stats_weekly_fasts': 'Puasa Dicatat (7 hari terakhir)',
      'qaza_backlog': 'Tunggakan Qadha Aktif',
      'back_to_home': 'Kembali ke Beranda',
      'active_preset': 'Tema Warna Aktif',
      'completed': 'selesai',
      'days': 'hari',
      'of_total': 'dari',
      'exit_warning': 'Tekan sekali lagi untuk keluar',
      'current_prayer': 'Shalat Sekarang',
      'next_prayer': 'Shalat Berikutnya',
      'left': 'tersisa',
      'time_elapsed': 'berlalu',
      'remaining': 'tersisa',
      'quiz': 'Kuis Al-Quran',
      'tafsir_review': 'Tinjauan Tafsir',
      'quiz_question_count': 'Pertanyaan',
      'quiz_points': 'Poin',
      'quiz_next': 'Pertanyaan Berikutnya',
      'quiz_previous': 'Sebelumnya',
      'quiz_finish': 'Selesaikan Kuis',
      'quiz_lifetime_score': 'Skor Seumur Hidup',
      'quiz_completed_title': 'Kuis Harian Selesai!',
      'quiz_completed_sub': 'Anda telah menjawab ke-7 pertanyaan hari ini. Kembali besok untuk wawasan Al-Quran baru!',
      'quiz_syncing': 'Menyinkronkan kemajuan dengan server...',
      'quiz_synced': 'Kemajuan berhasil disinkronkan ke cloud',
      'quiz_correct': 'Benar',
      'quiz_incorrect': 'Salah',
      'quiz_tafsir_insight': 'Wawasan Tafsir',
      'quiz_pts': 'poin',
      'no_questions_available': 'Tidak Ada Pertanyaan',
      'no_questions_available_sub': 'Tidak ada pertanyaan untuk hari ini. Silakan coba lagi nanti.',
      'quiz_no_results': 'Tidak ada hasil. Harap selesaikan kuis hari ini terlebih dahulu.',
      'quiz_sync_error_timeout': 'Koneksi habis waktu. Kemajuan disimpan secara lokal.',
      'quiz_sync_error_failed': 'Sinkronisasi gagal. Kemajuan disimpan secara lokal.',
      'explore_tools': 'Hub Spiritual',
      'hub_mosques_sub': 'Cari masjid terdekat',
      'hub_quiz_sub': 'Uji wawasan Al-Quran',
      'hub_tracker_sub': 'Catat shalat harian',
      'hub_qaza_sub': 'Lacak tunggakan qadha',
      'hub_profile_sub': 'Lihat statistik & catatan',
      'hub_settings_sub': 'Tema & perhitungan',
      'qibla_finder': 'Pencari Kiblat',
      'hub_qibla_sub': 'Temukan arah Mekah',
      'qibla_direction': 'Arah Kiblat',
      'qibla_searching': 'Menentukan lokasi…',
      'qibla_error': 'Tidak dapat menentukan arah Kiblat. Harap aktifkan akses lokasi.',
      'qibla_sensor_unavailable': 'Sensor kompas tidak tersedia di perangkat ini.',
      'special_timings': 'Periode Dilarang',
      'view_calendar': 'Kalender Jadwal Shalat',
      'calendar_subtitle': 'Lihat jadwal mingguan, bulanan & tanggal khusus',
      'tab_week': 'Mingguan',
      'tab_month': 'Bulanan',
      'tab_date': 'Pilih Tanggal',
      'tap_view_details': 'Ketuk untuk detail',
      'no_timings_found': 'Jadwal tidak ditemukan',
      'forbidden_status': 'Status Izin Shalat',
      'prayer_allowed': 'Shalat diperbolehkan',
      'prayer_forbidden': 'Shalat sunnah dilarang',
      'tahajjud_prayer': 'Shalat Tahajjud',
      'tahajjud_desc': 'Shalat malam hari',
      'tahajjud_best': 'Tahajjud (Waktu Terbaik)',
      'ishraq_prayer': 'Shalat Ishraq',
      'chasht_duha': 'Shalat Duha (Chasht)',
      'chasht_desc': 'Shalat sunnah dhuha',
      'chasht_info_title': 'Tentang Shalat Duha (Chasht)',
      'chasht_info_body': 'Duha (atau Chasht) adalah shalat sunnah yang dikerjakan saat matahari mulai naik tinggi. Waktunya dimulai 45 menit setelah matahari terbit hingga 10 menit sebelum masuk waktu Zuhur. Salat ini mendatangkan keberkahan rezeki.',
      'ishraq_desc': 'Shalat awal pagi',
      'forbidden_sunrise': 'Waktu Dilarang (Terbit Matahari)',
      'forbidden_zawal': 'Waktu Dilarang (Zawal / Tengah Hari)',
      'forbidden_sunset': 'Waktu Dilarang (Jelang Maghrib)',
      'forbidden_time': 'Waktu Dilarang',
      'prayer_not_permitted': 'Shalat tidak diperbolehkan',
      'tahajjud_active': 'Waktu Tahajjud Aktif',
      'state_active': 'Sekarang',
      'state_upcoming': 'Mendatang',
      'ishraq_active': 'Waktu Ishraq Aktif',
      'chasht_duha_active': 'Waktu Duha (Chasht) Aktif',
      'select_language': 'Pilih Bahasa',
      'confirm': 'Konfirmasi',
      'lang_detect_desc': 'Kami mendeteksi bahasa Anda berdasarkan lokasi Anda. Silakan ubah jika perlu.',
      'tahajjud_info_title': 'Tentang Salat Tahajjud',
      'tahajjud_info_body': 'Tahajjud adalah salat sunnah malam hari yang dilakukan setelah bangun tidur. Waktunya membentang dari setelah Isya hingga sebelum Subuh, dengan waktu terbaik di sepertiga malam terakhir. Salat ini mendatangkan kedekatan spiritual dan ketenangan hati.',
      'ishraq_info_title': 'Tentang Salat Ishraq (Duha)',
      'ishraq_info_body': 'Ishraq (awal waktu Duha) adalah salat sunnah di pagi hari. Waktunya dimulai 15 menit setelah matahari terbit dan berakhir 10 menit sebelum masuk waktu Dzuhur. Salat ini mendatangkan keberkahan dan pahala yang sangat besar.',
      'close': 'Tutup',
      'am': 'AM',
      'pm': 'PM',
      'ishraq': 'Ishraq',
    },
    'ms': {
      'app_title': 'Adeen • عدين',
      'sehri': 'Sahur Tamat',
      'iftar': 'Waktu Berbuka',
      'fajr': 'Subuh',
      'sunrise': 'Syuruk',
      'dhuhr': 'Zohor',
      'jumah_prayer': 'Jumaat',
      'asr': 'Asar',
      'maghrib': 'Maghrib',
      'isha': 'Isyak',
      'imsak': 'Imsak',
      'prayer_tracker': 'Pelacak Solat Harian',
      'qaza_tracker': 'Pelacak Qadha',
      'fasting_tracker': 'Pelacak Puasa Ramadan',
      'fasted_today': 'Puasa Hari Ini?',
      'fasting_completed': 'Alhamdulillah, Puasa Selesai!',
      'fasting_not_completed': 'Puasa belum dimulakan/dicatat',
      'prayers_logged': 'Solat Dicatat',
      'mosques': 'Masjid Berdekatan',
      'mosque_data_disclaimer': 'Nota: Butiran dan lokasi masjid diambil dari Google Maps dan mungkin tidak tepat sepenuhnya.',
      'search_mosques': 'Tapis Masjid',
      'facility_women': 'Ruang Wanita',
      'facility_parking': 'Kawasan Parkir',
      'facility_jummah': 'Beberapa Gelombang Solat Jumaat',
      'iqamah_time': 'Iqamah',
      'suggest_iqamah': 'Cadangkan Waktu Iqamah',
      'get_directions': 'Petunjuk Arah',
      'update_iqamah_title': 'Cadangkan Waktu Iqamah baru',
      'update_success': 'Waktu Iqamah berjaya dikemaskini!',
      'enter_time': 'Pilih Waktu',
      'cancel': 'Batal',
      'change': 'Ubah',
      'today_prayers': 'Solat Hari Ini',
      'hijri_month_1': 'Muharram',
      'hijri_month_2': 'Safar',
      'hijri_month_3': 'Rabiul Awal',
      'hijri_month_4': 'Rabiul Akhir',
      'hijri_month_5': 'Jumadil Awal',
      'hijri_month_6': 'Jumadil Akhir',
      'hijri_month_7': 'Rejab',
      'hijri_month_8': 'Syaaban',
      'hijri_month_9': 'Ramadhan',
      'hijri_month_10': 'Syawal',
      'hijri_month_11': 'Dzulkaedah',
      'hijri_month_12': 'Dzulhijjah',
      'save': 'Simpan',
      'distance': 'Jarak',
      'km': 'km',
      'method': 'Kaedah Pengiraan',
      'calculation_settings': 'Tetapan Pengiraan',
      'method_karachi': 'Universiti Sains Islam, Karachi',
      'method_isna': 'Persatuan Islam Amerika Utara (ISNA)',
      'method_mwl': 'Liga Dunia Muslim (MWL)',
      'method_umm_al_qura': 'Universiti Umm Al-Qura, Makkah',
      'method_egyptian': 'Lembaga Ukur Am Mesir',
      'method_gulf': 'Wilayah Teluk',
      'method_kuwait': 'Kuwait',
      'method_qatar': 'Qatar',
      'method_singapore': 'MUIS (Singapura)',
      'method_turkey': 'Diyanet (Turki)',
      'method_jafari': 'Institut Leva, Qom (Jafari)',
      'method_tehran': 'Institut Geofizik, Univ. Tehran',
      'method_france': 'Pertubuhan Islam Perancis (UOIF)',
      'method_russia': 'Pentadbiran Rohani Muslim Rusia',
      'method_moonsighting': 'Jawatankuasa Rukyah Sedunia',
      'method_dubai': 'Dubai (Eksperimental)',
      'method_jakim': 'JAKIM, Malaysia',
      'method_tunisia': 'Tunisia',
      'method_algeria': 'Algeria',
      'method_kemenag': 'Kemenag (Indonesia)',
      'method_morocco': 'Maghribi',
      'method_portugal': 'Komuniti Islam Lisboa, Portugal',
      'method_jordan': 'Kementerian Awqaf, Jordan',
      'juristic_method': 'Mazhab (Kiraan Asar)',
      'school_standard': 'Standard (Syafi\'i, Maliki, Hanbali)',
      'school_hanafi': 'Hanafi',
      'next_prayer_in': 'Solat Seterusnya dalam',
      'sehri_ends_in': 'Sahur tamat dalam',
      'iftar_in': 'Berbuka puasa dalam',
      'offline_msg': 'Mod Luar Talian • Cache Tempatan',
      'loading': 'Mengemas kini jadual solat...',
      'bismillah': 'Dengan nama Allah Yang Maha Pemurah lagi Maha Penyayang',
      'change_lang': 'Tukar Bahasa / Language',
      'active_lang': 'Bahasa Melayu',
      'settings': 'Tetapan & Keutamaan',
      'home': 'Utama',
      'theme_mode': 'Mod Tema',
      'theme_system': 'Default Sistem',
      'theme_light': 'Mod Cerah',
      'theme_dark': 'Mod Gelap',
      'color_scheme': 'Skema Warna Tema',
      'color_emerald': 'Hijau Zamrud',
      'color_sapphire': 'Biru Nilam',
      'color_ruby': 'Merah Delima',
      'profile': 'Profil & Statistik',
      'stats_weekly_prayers': 'Solat Mingguan Selesai',
      'stats_weekly_fasts': 'Puasa Dicatat (7 hari terakhir)',
      'qaza_backlog': 'Tunggakan Qadha Aktif',
      'back_to_home': 'Kembali ke Laman Utama',
      'active_preset': 'Tema Warna Aktif',
      'completed': 'selesai',
      'days': 'hari',
      'of_total': 'daripada',
      'exit_warning': 'Tekan sekali lagi untuk keluar',
      'current_prayer': 'Solat Sekarang',
      'next_prayer': 'Solat Seterusnya',
      'left': 'tinggal',
      'time_elapsed': 'berlalu',
      'remaining': 'tinggal',
      'quiz': 'Kuiz Al-Quran',
      'tafsir_review': 'Tinjauan Tafsir',
      'quiz_question_count': 'Soalan',
      'quiz_points': 'Mata',
      'quiz_next': 'Soalan Seterusnya',
      'quiz_previous': 'Sebelumnya',
      'quiz_finish': 'Selesaikan Kuiz',
      'quiz_lifetime_score': 'Skor Sepanjang Hayat',
      'quiz_completed_title': 'Kuiz Harian Selesai!',
      'quiz_completed_sub': 'Anda telah menjawab semua 7 soalan untuk hari ini. Kembali esok untuk wawasan Al-Quran yang baru!',
      'quiz_syncing': 'Menyinkronkan kemajuan dengan pelayan...',
      'quiz_synced': 'Kemajuan berjaya disinkronkan ke awan',
      'quiz_correct': 'Betul',
      'quiz_incorrect': 'Salah',
      'quiz_tafsir_insight': 'Wawasan Tafsir',
      'quiz_pts': 'mata',
      'no_questions_available': 'Tiada Soalan Tersedia',
      'no_questions_available_sub': 'Tiada soalan dikonfigurasikan untuk hari ini. Sila cuba lagi kemudian.',
      'quiz_no_results': 'Tiada keputusan tersedia. Sila selesaikan kuiz hari ini terlebih dahulu.',
      'quiz_sync_error_timeout': 'Sambungan tamat masa. Kemajuan disimpan secara tempatan.',
      'quiz_sync_error_failed': 'Penyinkronan gagal. Kemajuan disimpan secara tempatan.',
      'explore_tools': 'Hub Spiritual',
      'hub_mosques_sub': 'Cari masjid berdekatan',
      'hub_quiz_sub': 'Uji wawasan Al-Quran',
      'hub_tracker_sub': 'Catat solat harian',
      'hub_qaza_sub': 'Jejak tunggakan qada',
      'hub_profile_sub': 'Lihat statistik & rekod',
      'hub_settings_sub': 'Tema & pengiraan',
      'qibla_finder': 'Pencari Kiblat',
      'hub_qibla_sub': 'Cari arah Mekah',
      'qibla_direction': 'Arah Kiblat',
      'qibla_searching': 'Menentukan lokasi…',
      'qibla_error': 'Tidak dapat menentukan arah Kiblat. Sila aktifkan akses lokasi.',
      'qibla_sensor_unavailable': 'Sensor kompas tidak tersedia pada peranti ini.',
      'special_timings': 'Tempoh Dilarang',
      'view_calendar': 'Kalendar Jadual Solat',
      'calendar_subtitle': 'Lihat jadual mingguan, bulanan & tarikh khusus',
      'tab_week': 'Mingguan',
      'tab_month': 'Bulanan',
      'tab_date': 'Pilih Tarikh',
      'tap_view_details': 'Ketik untuk butiran',
      'no_timings_found': 'Jadual tidak ditemui',
      'forbidden_status': 'Status Keizinan Solat',
      'prayer_allowed': 'Solat dibenarkan',
      'prayer_forbidden': 'Solat sunat dilarang',
      'tahajjud_prayer': 'Solat Tahajjud',
      'tahajjud_desc': 'Solat malam hari',
      'tahajjud_best': 'Tahajjud (Waktu Terbaik)',
      'ishraq_prayer': 'Solat Isyraq',
      'chasht_duha': 'Solat Duha (Chasht)',
      'chasht_desc': 'Solat sunat dhuha',
      'chasht_info_title': 'Mengenai Solat Duha (Chasht)',
      'chasht_info_body': 'Duha (atau Chasht) ialah solat sunat yang didirikan apabila matahari mula naik tinggi. Waktunya bermula 45 minit selepas terbit matahari sehingga 10 minit sebelum masuk waktu Zohor. Solat ini membawa keberkatan rezeki.',
      'ishraq_desc': 'Solat awal pagi',
      'forbidden_sunrise': 'Tempoh Dilarang (Syuruk)',
      'forbidden_zawal': 'Tempoh Dilarang (Zawal / Tengah Hari)',
      'forbidden_sunset': 'Tempoh Dilarang (Jelang Maghrib)',
      'forbidden_time': 'Waktu Dilarang',
      'prayer_not_permitted': 'Solat tidak dibenarkan',
      'tahajjud_active': 'Waktu Tahajjud Aktif',
      'state_active': 'Sekarang',
      'state_upcoming': 'Akan Datang',
      'ishraq_active': 'Waktu Isyraq Aktif',
      'chasht_duha_active': 'Waktu Duha (Chasht) Aktif',
      'select_language': 'Pilih Bahasa',
      'confirm': 'Sahkan',
      'lang_detect_desc': 'Kami mengesan bahasa anda berdasarkan lokasi anda. Sila ubah jika perlu.',
      'tahajjud_info_title': 'Mengenai Solat Tahajjud',
      'tahajjud_info_body': 'Tahajjud ialah solat sunat malam yang didirikan setelah bangun tidur. Waktunya bermula selepas Isyak hingga sebelum Subuh, dengan waktu terbaik ialah sepertiga malam yang terakhir. Solat ini membawa kedekatan spiritual dan ketenangan jiwa.',
      'ishraq_info_title': 'Mengenai Solat Isyraq (Duha)',
      'ishraq_info_body': 'Isyraq (permulaan waktu Duha) ialah solat sunat pada waktu pagi. Waktunya bermula 15 minit selepas terbit matahari sehingga 10 minit sebelum masuk waktu Zohor. Mendirikan solat ini mendatangkan keberkatan dan ganjaran yang besar.',
      'close': 'Tutup',
      'am': 'AM',
      'pm': 'PM',
      'ishraq': 'Isyraq',
    },
    'tr': {
      'app_title': 'Adeen • عدين',
      'sehri': 'Sahur Bitiş',
      'iftar': 'İftar Vakti',
      'fajr': 'İmsak / Sabah',
      'sunrise': 'Güneş',
      'dhuhr': 'Öğle',
      'jumah_prayer': 'Cuma',
      'asr': 'İkindi',
      'maghrib': 'Akşam',
      'isha': 'Yatsı',
      'imsak': 'İmsak',
      'prayer_tracker': 'Günlük Namaz Takipçisi',
      'qaza_tracker': 'Kaza Namazı Takibi',
      'fasting_tracker': 'Ramazan Oruç Takipçisi',
      'fasted_today': 'Bugün Oruçlu musunuz?',
      'fasting_completed': 'Alhamdülillah, Oruç Tamamlandı!',
      'fasting_not_completed': 'Oruç henüz kaydedilmedi',
      'prayers_logged': 'Kaydedilen Namazlar',
      'mosques': 'Yakındaki Camiler',
      'mosque_data_disclaimer': 'Not: Cami detayları ve konumları Google Haritalar\'dan alınmıştır ve tamamen doğru olmayabilir.',
      'search_mosques': 'Cami Özellik Filtresi',
      'facility_women': 'Kadınlar Bölümü',
      'facility_parking': 'Otopark Alanı',
      'facility_jummah': 'Çoklu Cuma Namazı',
      'iqamah_time': 'Kamet',
      'suggest_iqamah': 'Kamet Vakti Öner',
      'get_directions': 'Yol Tarifi Al',
      'update_iqamah_title': 'Kamet Vakti Öner',
      'update_success': 'Kamet vakti başarıyla güncellendi!',
      'enter_time': 'Saat Seç',
      'cancel': 'İptal',
      'change': 'Değiştir',
      'today_prayers': 'Bugünün Namazları',
      'hijri_month_1': 'Muharrem',
      'hijri_month_2': 'Safer',
      'hijri_month_3': 'Rebiülevvel',
      'hijri_month_4': 'Rebiülahir',
      'hijri_month_5': 'Cemaziyelevvel',
      'hijri_month_6': 'Cemaziyelahir',
      'hijri_month_7': 'Recep',
      'hijri_month_8': 'Şaban',
      'hijri_month_9': 'Ramazan',
      'hijri_month_10': 'Şevval',
      'hijri_month_11': 'Zilkade',
      'hijri_month_12': 'Zilhicce',
      'save': 'Kaydet',
      'distance': 'Mesafe',
      'km': 'km',
      'method': 'Hesaplama Yöntemi',
      'calculation_settings': 'Hesaplama Ayarları',
      'method_karachi': 'Karaçi İslami İlimler Üniversitesi',
      'method_isna': 'Kuzey Amerika İslam Topluluğu (ISNA)',
      'method_mwl': 'Müslüman Dünya Birliği (MWL)',
      'method_umm_al_qura': 'Umm Al-Qura Üniversitesi, Mekke',
      'method_egyptian': 'Mısır Genel Araştırma Kurumu',
      'method_gulf': 'Körfez Bölgesi',
      'method_kuwait': 'Kuveyt',
      'method_qatar': 'Katar',
      'method_singapore': 'MUIS (Singapur)',
      'method_turkey': 'Diyanet İşleri Başkanlığı (Türkiye)',
      'method_jafari': 'Leva Enstitüsü, Kum (Caferi)',
      'method_tehran': 'Jeofizik Enstitüsü, Tahran Üniversitesi',
      'method_france': 'İslam Birliği Teşkilatı, Fransa',
      'method_russia': 'Rusya Müslümanları Ruhani İdaresi',
      'method_moonsighting': 'Dünya Hilal Gözlem Komitesi',
      'method_dubai': 'Dubai (Deneysel)',
      'method_jakim': 'JAKIM, Malezya',
      'method_tunisia': 'Tunus',
      'method_algeria': 'Cezayir',
      'method_kemenag': 'Kemenag (Endonezya)',
      'method_morocco': 'Fas',
      'method_portugal': 'İslam Cemiyeti Lizbon, Portekiz',
      'method_jordan': 'Evkaf Bakanlığı, Ürdün',
      'juristic_method': 'Fıkhi Mezhep (Asr)',
      'school_standard': 'Standart (Şafii, Maliki, Hanbeli)',
      'school_hanafi': 'Hanefi',
      'next_prayer_in': 'Sıradaki Ezan',
      'sehri_ends_in': 'Sahur bitimine kalan',
      'iftar_in': 'İftara kalan süre',
      'offline_msg': 'Çevrimdışı Mod • Yerel Önbellek',
      'loading': 'Namaz vakitleri güncelleniyor...',
      'bismillah': 'Rahman ve Rahim olan Allah\'ın adıyla',
      'change_lang': 'Dili Değiştir / Language',
      'active_lang': 'Türkçe',
      'settings': 'Ayarlar ve Tercihler',
      'home': 'Ana Sayfa',
      'theme_mode': 'Tema Modu',
      'theme_system': 'Sistem Varsayılanı',
      'theme_light': 'Açık Tema',
      'theme_dark': 'Karanlık Tema',
      'color_scheme': 'Renk Teması Önayarı',
      'color_emerald': 'Zümrüt Yeşili',
      'color_sapphire': 'Safir Mavisi',
      'color_ruby': 'Yakut Kırmızısı',
      'profile': 'Profil & İstatistikler',
      'stats_weekly_prayers': 'Haftalık Kılınan Namazlar',
      'stats_weekly_fasts': 'Tutulan Oruçlar (Son 7 gün)',
      'qaza_backlog': 'Kaza Namazı Borcu',
      'back_to_home': 'Ana Sayfaya Dön',
      'active_preset': 'Aktif Renk Teması',
      'completed': 'tamamlandı',
      'days': 'gün',
      'of_total': '/',
      'exit_warning': 'Çıkmak için tekrar geri basın',
      'current_prayer': 'Mevcut Namaz',
      'next_prayer': 'Sıradaki Namaz',
      'left': 'kaldı',
      'time_elapsed': 'geçen',
      'remaining': 'kalan',
      'quiz': 'Kuran Bilgi Yarışması',
      'tafsir_review': 'Tefsir İncelemesi',
      'quiz_question_count': 'Soru',
      'quiz_points': 'Puan',
      'quiz_next': 'Sonraki Soru',
      'quiz_previous': 'Önceki',
      'quiz_finish': 'Yarışmayı Bitir',
      'quiz_lifetime_score': 'Toplam Puan',
      'quiz_completed_title': 'Günlük Yarışma Tamamlandı!',
      'quiz_completed_sub': 'Bugünün 7 sorusunun tamamını cevapladınız. Yeni Kuran bilgileri için yarın tekrar gelin!',
      'quiz_syncing': 'İlerleme sunucuyla eşitleniyor...',
      'quiz_synced': 'İlerleme bulutla güvenli bir şekilde eşitlendi',
      'quiz_correct': 'Doğru',
      'quiz_incorrect': 'Yanlış',
      'quiz_tafsir_insight': 'Tefsir Analizi',
      'quiz_pts': 'puan',
      'no_questions_available': 'Kullanılabilir Soru Yok',
      'no_questions_available_sub': 'Bugün için yapılandırılmış soru yok. Lütfen daha sonra tekrar deneyin.',
      'quiz_no_results': 'Kullanılabilir sonuç yok. Lütfen önce bugünün yarışmasını tamamlayın.',
      'quiz_sync_error_timeout': 'Bağlantı zaman aşımına uğradı. İlerleme yerel olarak kaydedildi.',
      'quiz_sync_error_failed': 'Eşitleme başarısız oldu. İlerleme yerel olarak kaydedildi.',
      'explore_tools': 'Manevi Merkez',
      'hub_mosques_sub': 'Yakındaki camileri bul',
      'hub_quiz_sub': 'Kuran bilgisini test et',
      'hub_tracker_sub': 'Günlük namazları kaydet',
      'hub_qaza_sub': 'Kaza namazlarını takip et',
      'hub_profile_sub': 'İstatistikleri ve günlüğü gör',
      'hub_settings_sub': 'Temalar ve hesaplama',
      'qibla_finder': 'Kıble Bulucu',
      'hub_qibla_sub': 'Mekke yönünü bulun',
      'qibla_direction': 'Kıble Yönü',
      'qibla_searching': 'Konum belirleniyor…',
      'qibla_error': 'Kıble yönü belirlenemedi. Lütfen konum erişimine izin verin.',
      'qibla_sensor_unavailable': 'Bu cihazda pusula sensörü mevcut değil.',
      'special_timings': 'Kerahat Vaktleri',
      'view_calendar': 'Namaz Vakitleri Takvimi',
      'calendar_subtitle': 'Haftalık, aylık ve özel tarih vakitlerini görün',
      'tab_week': 'Haftalık',
      'tab_month': 'Aylık',
      'tab_date': 'Tarih Seç',
      'tap_view_details': 'Detaylar için dokunun',
      'no_timings_found': 'Vakit bulunamadı',
      'forbidden_status': 'Namaz Kılma Durumu',
      'prayer_allowed': 'Namazlar kılınabilir',
      'prayer_forbidden': 'Nafile namaz kılmak mekruhtur',
      'tahajjud_prayer': 'Teheccüd Namazı',
      'tahajjud_desc': 'Gece namazı',
      'tahajjud_best': 'Teheccüd (En Faziletli Vakit)',
      'ishraq_prayer': 'İşrak Namazı',
      'chasht_duha': 'Kuşluk (Duha) Namazı',
      'chasht_desc': 'Kuşluk nafile namazı',
      'chasht_info_title': 'Kuşluk (Duha) Namazı Hakkında',
      'chasht_info_body': 'Kuşluk (Duha), güneş yükseldiğinde kılınan nafile bir namazdır. Vakti güneşin doğuşundan 45 dakika sonra başlar ve öğleden 10 dakika önce sona erer. Rızık bolluğu ve eklemlerin sadakası için tavsiye edilen bir sünnettir.',
      'ishraq_desc': 'Kuşluk öncesi namaz',
      'forbidden_sunrise': 'Güneş Doğarken Kerahat Vakti',
      'forbidden_zawal': 'Öğle Öncesi Kerahat Vakti (Zeval)',
      'forbidden_sunset': 'Akşam Öncesi Kerahat Vakti (Grup)',
      'forbidden_time': 'Kerahat Vakti',
      'prayer_not_permitted': 'Namaz kılmak yasaktır',
      'tahajjud_active': 'Teheccüd Vakti Girdi',
      'state_active': 'Şu Anki',
      'state_upcoming': 'Gelecek',
      'ishraq_active': 'İşrak Vakti Girdi',
      'chasht_duha_active': 'Kuşluk (Duha) Vakti Girdi',
      'select_language': 'Dil Seçin',
      'confirm': 'Onayla',
      'lang_detect_desc': 'Konumunuza göre dilinizi tespit ettik. Değiştirmekten çekinmeyin.',
      'tahajjud_info_title': 'Teheccüd Namazı Hakkında',
      'tahajjud_info_body': 'Teheccüd, yatsıdan sonra uyuyup uyandıktan sonra kılınan nafile bir gece namazıdır. Vakti yatsıdan imsak vaktine kadardır; en faziletli zamanı gecenin son üçte biridir. Manevi yakınlık ve huzur vesilesidir.',
      'ishraq_info_title': 'İşrak (Duha) Namazı Hakkında',
      'ishraq_info_body': 'İşrak namazı (kuşluk vaktinin başlangıcı), sabah kılınan nafile bir namazdır. Vakti güneş doğduktan 15 dakika sonra başlar ve öğle vaktine 10 dakika kalaya kadar sürer. Kılınması büyük sevap ve bereket kaynağıdır.',
      'close': 'Kapat',
      'am': 'ÖÖ',
      'pm': 'ÖS',
      'ishraq': 'İşrak',
    },
    'fr': {
      'app_title': 'Adeen • عدين',
      'sehri': 'Fin du Sehri',
      'iftar': 'Heure de l\'Iftar',
      'fajr': 'Fajr',
      'sunrise': 'Lever du soleil',
      'dhuhr': 'Dhuhr',
      'jumah_prayer': 'Jumah',
      'asr': 'Asr',
      'maghrib': 'Maghrib',
      'isha': 'Isha',
      'imsak': 'Imsak',
      'prayer_tracker': 'Suivi des prières',
      'qaza_tracker': 'Suivi des prières Qaza',
      'fasting_tracker': 'Suivi du Jeûne du Ramadan',
      'fasted_today': 'Jeûnez-vous aujourd\'hui ?',
      'fasting_completed': 'Alhamdulillah, Jeûne Complété !',
      'fasting_not_completed': 'Jeûne non commencé/enregistré',
      'prayers_logged': 'Prières Enregistrées',
      'mosques': 'Mosquées à proximité',
      'mosque_data_disclaimer': 'Remarque : Les détails et emplacements des mosquées sont récupérés depuis Google Maps et peuvent ne pas être totalement exacts.',
      'search_mosques': 'Filtrer les mosquées',
      'facility_women': 'Espace femmes',
      'facility_parking': 'Parking disponible',
      'facility_jummah': 'Plusieurs prières du Vendredi',
      'iqamah_time': 'Iqamah',
      'suggest_iqamah': 'Suggérer une heure d\'Iqamah',
      'get_directions': 'Itinéraire',
      'update_iqamah_title': 'Suggérer l\'Iqamah',
      'update_success': 'Heure de l\'Iqamah mise à jour !',
      'enter_time': 'Sélectionner l\'heure',
      'cancel': 'Annuler',
      'change': 'Modifier',
      'today_prayers': 'Prières d\'aujourd\'hui',
      'hijri_month_1': 'Muharram',
      'hijri_month_2': 'Safar',
      'hijri_month_3': 'Rabi\' al-awwal',
      'hijri_month_4': 'Rabi\' ath-thani',
      'hijri_month_5': 'Joumada al-oula',
      'hijri_month_6': 'Joumada ath-thaniya',
      'hijri_month_7': 'Rajab',
      'hijri_month_8': 'Cha\'bane',
      'hijri_month_9': 'Ramadan',
      'hijri_month_10': 'Shawwal',
      'hijri_month_11': 'Dhou al-qi\'dah',
      'hijri_month_12': 'Dhou al-hijjah',
      'save': 'Enregistrer',
      'distance': 'Distance',
      'km': 'km',
      'method': 'Méthode de calcul',
      'calculation_settings': 'Paramètres de calcul',
      'method_karachi': 'Université des Sciences Islamiques, Karachi',
      'method_isna': 'Société Islamique d\'Amérique du Nord (ISNA)',
      'method_mwl': 'Ligue Islamique Mondiale (LIM)',
      'method_umm_al_qura': 'Université Umm Al-Qura, La Mecque',
      'method_egyptian': 'Autorité Générale Égyptienne de l\'Enquête',
      'method_gulf': 'Région du Golfe',
      'method_kuwait': 'Koweït',
      'method_qatar': 'Qatar',
      'method_singapore': 'MUIS (Singapour)',
      'method_turkey': 'Diyanet (Turquie)',
      'method_jafari': 'Institut Leva, Qom (Jafari)',
      'method_tehran': 'Institut de Géophysique, Univ. de Téhéran',
      'method_france': 'Union des Organisations Islamiques de France',
      'method_russia': 'Direction Spirituelle des Musulmans de Russie',
      'method_moonsighting': 'Comité Mondial d\'Observation du Croissant',
      'method_dubai': 'Dubaï (Expérimental)',
      'method_jakim': 'JAKIM, Malaisie',
      'method_tunisia': 'Tunisie',
      'method_algeria': 'Algérie',
      'method_kemenag': 'Kemenag (Indonésie)',
      'method_morocco': 'Maroc',
      'method_portugal': 'Communauté Islamique de Lisbonne, Portugal',
      'method_jordan': 'Ministère des Awqaf, Jordanie',
      'juristic_method': 'Méthode Juridique (Asr)',
      'school_standard': 'Standard (Chafi\'i, Maliki, Hanbali)',
      'school_hanafi': 'Hanafite',
      'next_prayer_in': 'Prochaine prière dans',
      'sehri_ends_in': 'Fin du sahur dans',
      'iftar_in': 'Iftar dans',
      'offline_msg': 'Mode Hors-ligne • Cache Local',
      'loading': 'Mise à jour des horaires...',
      'bismillah': 'Au nom d\'Allah, le Tout Miséricordieux, le Très Miséricordieux',
      'change_lang': 'Changer de Langue / Language',
      'active_lang': 'Français',
      'settings': 'Paramètres & Préférences',
      'home': 'Accueil',
      'theme_mode': 'Mode Thème',
      'theme_system': 'Défaut Système',
      'theme_light': 'Mode Clair',
      'theme_dark': 'Mode Sombre',
      'color_scheme': 'Palette de Couleurs',
      'color_emerald': 'Vert Émeraude',
      'color_sapphire': 'Bleu Saphir',
      'color_ruby': 'Rouge Rubis',
      'profile': 'Profil & Statistiques',
      'stats_weekly_prayers': 'Prières hebdomadaires complétées',
      'stats_weekly_fasts': 'Jeûnes enregistrés (7 derniers jours)',
      'qaza_backlog': 'Prières Qaza en retard',
      'back_to_home': 'Retour à l\'accueil',
      'active_preset': 'Thème de couleur actif',
      'completed': 'complétée(s)',
      'days': 'jours',
      'of_total': 'sur',
      'exit_warning': 'Appuyez à nouveau pour quitter',
      'current_prayer': 'Prière Actuelle',
      'next_prayer': 'Prochaine Prière',
      'left': 'restant',
      'time_elapsed': 'écoulé',
      'remaining': 'restant',
      'quiz': 'Quiz Coranique',
      'tafsir_review': 'Revue de Tafsir',
      'quiz_question_count': 'Question',
      'quiz_points': 'Points',
      'quiz_next': 'Question Suivante',
      'quiz_previous': 'Précédent',
      'quiz_finish': 'Terminer le Quiz',
      'quiz_lifetime_score': 'Score Total',
      'quiz_completed_title': 'Quiz Quotidien Terminé !',
      'quiz_completed_sub': 'Vous avez répondu aux 7 questions du jour. Revenez demain pour de nouvelles analyses coraniques !',
      'quiz_syncing': 'Synchronisation de la progression...',
      'quiz_synced': 'Progression synchronisée sur le cloud',
      'quiz_correct': 'Correct',
      'quiz_incorrect': 'Incorrect',
      'quiz_tafsir_insight': 'Aperçu du Tafsir',
      'quiz_pts': 'pts',
      'no_questions_available': 'Aucune question disponible',
      'no_questions_available_sub': 'Aucune question n\'est configurée pour aujourd\'hui. Veuillez réessayer plus tard.',
      'quiz_no_results': 'Aucun résultat disponible. Veuillez d\'abord terminer le quiz d\'aujourd\'hui.',
      'quiz_sync_error_timeout': 'Délai de connexion dépassé. Progression enregistrée localement.',
      'quiz_sync_error_failed': 'Échec de la synchronisation. Progression enregistrée localement.',
      'explore_tools': 'Hub Spirituel',
      'hub_mosques_sub': 'Trouver les mosquées',
      'hub_quiz_sub': 'Tester vos connaissances',
      'hub_tracker_sub': 'Enregistrer les prières',
      'hub_qaza_sub': 'Suivre les prières manquées',
      'hub_profile_sub': 'Statistiques & historique',
      'hub_settings_sub': 'Thèmes & calculs',
      'qibla_finder': 'Localisateur de la Qibla',
      'hub_qibla_sub': 'Trouvez la direction de La Mecque',
      'qibla_direction': 'Direction de la Qibla',
      'qibla_searching': 'Détermination de la position…',
      'qibla_error': 'Impossible de déterminer la direction de la Qibla. Veuillez activer l\'accès à la localisation.',
      'qibla_sensor_unavailable': 'Le capteur de boussole n\'est pas disponible sur cet appareil.',
      'special_timings': 'Périodes Interdites',
      'view_calendar': 'Calendrier des Prières',
      'calendar_subtitle': 'Voir les horaires hebdomadaires, mensuels et personnalisés',
      'tab_week': 'Hebdomadaire',
      'tab_month': 'Mensuel',
      'tab_date': 'Choisir Date',
      'tap_view_details': 'Appuyer pour les détails',
      'no_timings_found': 'Aucun horaire trouvé',
      'forbidden_status': 'Statut d\'autorisation de prière',
      'prayer_allowed': 'Les prières sont autorisées',
      'prayer_forbidden': 'Prières volontaires interdites',
      'tahajjud_prayer': 'Prière du Tahajjud',
      'tahajjud_desc': 'Prière nocturne',
      'tahajjud_best': 'Tahajjud (Meilleur Moment)',
      'ishraq_prayer': 'Prière de l\'Ishraq',
      'chasht_duha': 'Prière de Chasht (Duha)',
      'chasht_desc': 'Prière volontaire de fin de matinée',
      'chasht_info_title': 'À propos de la prière de Chasht (Duha)',
      'chasht_info_body': 'Le Chasht (ou Duha) est une prière volontaire accomplie lorsque le soleil est haut. Sa période commence 45 minutes après le lever du soleil et se termine 10 minutes avant le Dhuhr. C\'est une Sunnah recommandée apportant l\'abondance.',
      'ishraq_desc': 'Prière après le lever du soleil',
      'forbidden_sunrise': 'Période interdite (Lever du soleil)',
      'forbidden_zawal': 'Période interdite (Zenith)',
      'forbidden_sunset': 'Période interdite (Coucher du soleil)',
      'forbidden_time': 'Temps interdit',
      'prayer_not_permitted': 'La prière n\'est pas autorisée',
      'tahajjud_active': 'Le temps du Tahajjud est actif',
      'state_active': 'Présente',
      'state_upcoming': 'Prochaine',
      'ishraq_active': 'Le temps de l\'Ishraq est actif',
      'chasht_duha_active': 'Le temps de Chasht (Duha) est actif',
      'select_language': 'Choisir la langue',
      'confirm': 'Confirmer',
      'lang_detect_desc': 'Nous avons détecté votre langue en fonction de votre emplacement. N\'hésitez pas à la modifier.',
      'tahajjud_info_title': 'À propos de la prière de Tahajjud',
      'tahajjud_info_body': 'Le Tahajjud est une prière nocturne volontaire accomplie après s\'être réveillé. Sa période s\'étend de l\'Isha jusqu\'au Fajr, le meilleur moment étant le dernier tiers de la nuit. C\'est une Sunnah fortement recommandée apportant paix et élévation spirituelle.',
      'ishraq_info_title': 'À propos de la prière d\'Ishraq (Duha)',
      'ishraq_info_body': 'L\'Ishraq (début de la prière de Duha) est une prière matinale volontaire. Sa période commence 15 minutes après le lever du soleil et se termine 10 minutes avant le Dhuhr. L\'accomplir apporte d\'immenses bénédictions.',
      'close': 'Fermer',
      'am': 'AM',
      'pm': 'PM',
      'ishraq': 'Ishraq',
    }
  };

  String localizeDigits(String input) {
    final String lang = locale.languageCode;
    Map<String, String>? mapping;
    if (lang == 'bn') {
      mapping = {
        '0': '০', '1': '১', '2': '২', '3': '৩', '4': '৪',
        '5': '৫', '6': '৬', '7': '৭', '8': '৮', '9': '৯',
      };
    } else if (lang == 'ar') {
      mapping = {
        '0': '٠', '1': '١', '2': '٢', '3': '٣', '4': '٤',
        '5': '٥', '6': '٦', '7': '٧', '8': '٨', '9': '٩',
      };
    } else if (lang == 'ur') {
      mapping = {
        '0': '۰', '1': '۱', '2': '۲', '3': '۳', '4': '۴',
        '5': '۵', '6': '۶', '7': '۷', '8': '۸', '9': '۹',
      };
    } else if (lang == 'hi') {
      mapping = {
        '0': '०', '1': '१', '2': '२', '3': '३', '4': '४',
        '5': '५', '6': '६', '7': '७', '8': '८', '9': '९',
      };
    }

    if (mapping == null) return input;

    final buffer = StringBuffer();
    for (int i = 0; i < input.length; i++) {
      final char = input[i];
      buffer.write(mapping[char] ?? char);
    }
    return buffer.toString();
  }

  String translate(String key) {
    final val = _localizedValues[locale.languageCode]?[key] ?? key;
    return localizeDigits(val);
  }

  bool get isRTL => locale.languageCode == 'ar' || locale.languageCode == 'ur';

  String formatHijriDate(String hijriStr) {
    if (hijriStr.isEmpty) return '';
    List<String> parts = [];
    if (hijriStr.contains('-')) {
      parts = hijriStr.split('-');
    } else {
      // Split by space and remove any empty items caused by multiple spaces
      parts = hijriStr.split(' ').where((e) => e.isNotEmpty).toList();
    }

    if (parts.length < 3) return localizeDigits(hijriStr);

    final String day = parts[0];
    final String monthRaw = parts[1];
    final String year = parts[2];

    int? monthNum = int.tryParse(monthRaw);

    if (monthNum == null) {
      final String monthClean = monthRaw
          .toLowerCase()
          .replaceAll('ā', 'a')
          .replaceAll('ī', 'i')
          .replaceAll('ū', 'u')
          .replaceAll('ḍ', 'd')
          .replaceAll('ḥ', 'h')
          .replaceAll('ṣ', 's')
          .replaceAll('ṭ', 't')
          .replaceAll('z̄', 'z')
          .replaceAll('z', 'z')
          .replaceAll(RegExp(r"[^a-z']"), '');
      if (monthClean.contains('muharram') || monthClean.contains('محرم')) {
        monthNum = 1;
      } else if (monthClean.contains('safar') || monthClean.contains('صفر')) {
        monthNum = 2;
      } else if (monthClean.contains('rabi') && (monthClean.contains('awwal') || monthClean.contains('أول') || monthClean.contains(' i') || monthClean.contains('i\u0304'))) {
        monthNum = 3;
      } else if (monthClean.contains('rabi') && (monthClean.contains('thani') || monthClean.contains('ثاني') || monthClean.contains(' ii') || monthClean.contains('i\u0304i\u0304'))) {
        monthNum = 4;
      } else if (monthClean.contains('jumada') && (monthClean.contains('awwal') || monthClean.contains('أولى') || monthClean.contains(' i') || monthClean.contains('i\u0304'))) {
        monthNum = 5;
      } else if (monthClean.contains('jumada') && (monthClean.contains('thani') || monthClean.contains('آخر') || monthClean.contains(' ii') || monthClean.contains('i\u0304i\u0304'))) {
        monthNum = 6;
      } else if (monthClean.contains('rajab') || monthClean.contains('رجب')) {
        monthNum = 7;
      } else if (monthClean.contains('shaban') || monthClean.contains('sha\'ban') || monthClean.contains('شعبان') || monthClean.contains('sha\u02bban')) {
        monthNum = 8;
      } else if (monthClean.contains('ramad') || monthClean.contains('رمضان')) {
        monthNum = 9;
      } else if (monthClean.contains('shaww') || monthClean.contains('شوال')) {
        monthNum = 10;
      } else if (monthClean.contains('qidah') || monthClean.contains('qi\'dah') || monthClean.contains('قعدة')) {
        monthNum = 11;
      } else if (monthClean.contains('hijjah') || monthClean.contains('حجة')) {
        monthNum = 12;
      }
    }

    if (monthNum != null && monthNum >= 1 && monthNum <= 12) {
      final String monthName = translate('hijri_month_$monthNum');
      return localizeDigits('$day $monthName $year');
    }

    return localizeDigits(hijriStr);
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => [
        'en',
        'ar',
        'bn',
        'hi',
        'ur',
        'id',
        'ms',
        'tr',
        'fr',
      ].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
